%% fit_J_l250_cube20.m — [J] joint fit for hung hexapole l=250, cube ±20 µm
%   Best-error operating point from validity sweep (0.29% mean error).
%   Saves .mat + generates LaTeX table in hung style.
%
%   Output:
%     magnetic_sim/ANSYS/backup/hung/data/J_l250_cube20_fit.mat
%     magnetic_sim/ANSYS/backup/hung/pdf/scripts/fitting_l250_cube20.tex

addpath(fullfile(fileparts(mfilename('fullpath')), '..', 'core'));
clear; clc;

%% ---- Paths ----
this_dir     = fileparts(mfilename('fullpath'));
results_root = fullfile(this_dir, '..', '..', 'results');
data_dir     = fullfile(this_dir, '..', '..', 'data');
tex_dir      = fullfile(this_dir, '..', '..', 'pdf', 'scripts');
if ~exist(data_dir, 'dir'), mkdir(data_dir); end
if ~exist(tex_dir, 'dir'),  mkdir(tex_dir);  end

%% ---- Geometry constants (l=250) ----
R_norm        = 250e-6;
R_norm_xy     = R_norm * sqrt(2/3);
R_norm_z      = R_norm / sqrt(3);
TIP_TO_ORIG   = R_norm * 1e6;     % 250 µm
N_c           = 70;               % coil turns (hung default)
mu_0          = 4*pi*1e-7;

pole_angles    = [0, 180, 120, 300, 60, 240];
pole_is_lower  = [1, 0, 1, 0, 0, 1];
layer_lab      = {'Lower', 'Upper', 'Lower', 'Upper', 'Upper', 'Lower'};

%% ---- Load 6 coils (filleted_l250_conv) ----
fprintf('Loading 6 hung coil datasets (l=250)...\n');
N_POLES = 6;
K_I = eye(N_POLES) - ones(N_POLES)/N_POLES;

half_xy = 20e-6;     % ±20 µm cube
half_z  = 20e-6;

coil_data = struct();
for k = 1:N_POLES
    dk = import_ansys_data(fullfile(results_root, sprintf('coil%d', k), 'filleted_l250_conv'), ...
                           'wp', sprintf('coil%d', k));
    mask = abs(dk.x) < half_xy & abs(dk.y) < half_xy & abs(dk.z) < half_z;
    n_in = sum(mask);
    N_max = 5000;
    if n_in > N_max
        idx_all = find(mask);
        rng(0);
        idx_sub = idx_all(randperm(n_in, N_max));
        mask = false(size(mask));
        mask(idx_sub) = true;
    end
    coil_data(k).px = dk.x(mask);
    coil_data(k).py = dk.y(mask);
    coil_data(k).pz = dk.z(mask);
    coil_data(k).bmag = sqrt(dk.bx(mask).^2 + dk.by(mask).^2 + dk.bz(mask).^2);
    coil_data(k).b_fem = [dk.bx(mask); dk.by(mask); dk.bz(mask)];
    coil_data(k).N = sum(mask);
    Iv = zeros(N_POLES, 1); Iv(k) = 1;
    coil_data(k).KI_w = K_I * Iv;
    fprintf('  coil%d: %d points\n', k, coil_data(k).N);
end

%% ---- Initial guess: pole tip 3D positions ----
pos_init = zeros(3, N_POLES);
for k = 1:N_POLES
    pos_init(1, k) = R_norm_xy * cosd(pole_angles(k));
    pos_init(2, k) = R_norm_xy * sind(pole_angles(k));
    if pole_is_lower(k)
        pos_init(3, k) = -R_norm_z;
    else
        pos_init(3, k) = +R_norm_z;
    end
end

%% ---- Fit ----
opts = optimset('TolX', 1e-10, 'TolFun', 1e-22, ...
                'MaxIter', 50000, 'MaxFunEvals', 50000, 'Display', 'off');
cost_fn = @(x) cjoint(x, coil_data, 1e-7, N_POLES);

fprintf('\n=== Fitting ===\n');
tic;
[xo, fv] = fminsearch(cost_fn, pos_init(:), opts);
elapsed = toc;
[~, Ck] = cjoint(xo, coil_data, 1e-7, N_POLES);
pos = reshape(xo, 3, N_POLES);

epc = zeros(1, N_POLES);
for k = 1:N_POLES
    Nk = coil_data(k).N;
    pw = [coil_data(k).px, coil_data(k).py, coil_data(k).pz];
    bu = evcf(pos, coil_data(k).KI_w, 1e-7, pw, N_POLES);
    bm = Ck(k) * bu;
    res = bm - coil_data(k).b_fem;
    em = sqrt(res(1:Nk).^2 + res(Nk+1:2*Nk).^2 + res(2*Nk+1:3*Nk).^2);
    epc(k) = mean(em ./ coil_data(k).bmag);
end
err_mean = mean(epc);

fprintf('  cost=%.4e, mean err=%.2f%%, time=%.0fs\n', fv, 100*err_mean, elapsed);

%% ---- Per-pole stats ----
ell_um  = vecnorm(pos) * 1e6;
tip2chg = ell_um - TIP_TO_ORIG;
R_a_per = N_c ./ (mu_0 * abs(Ck));

fprintf('\n  Pole | Layer | |ell| (µm) | Tip→Charge | err\n');
fprintf('  -------------------------------------------------\n');
for k = 1:N_POLES
    fprintf('   P%d  | %5s | %7.1f    | %+6.1f     | %.2f%%\n', ...
        k, layer_lab{k}, ell_um(k), tip2chg(k), 100*epc(k));
end

% Lower / Upper means
lower_idx = pole_is_lower == 1;
upper_idx = ~lower_idx;
mean_lower_ell = mean(ell_um(lower_idx));
mean_upper_ell = mean(ell_um(upper_idx));
mean_lower_t2c = mean(tip2chg(lower_idx));
mean_upper_t2c = mean(tip2chg(upper_idx));
Ra_lower = mean(R_a_per(lower_idx));
Ra_upper = mean(R_a_per(upper_idx));

%% ---- Save .mat ----
sv.pos          = pos;
sv.C_k          = Ck;
sv.cost         = fv;
sv.err_per_coil = epc;
sv.err_mean     = err_mean;
sv.ell_um       = ell_um;
sv.tip2chg_um   = tip2chg;
sv.R_a_per      = R_a_per;
sv.cube_half    = half_xy;
sv.K_I          = K_I;
sv.method       = 'J-l250-cube20';
mat_path = fullfile(data_dir, 'J_l250_cube20_fit.mat');
save(mat_path, '-struct', 'sv');
fprintf('\nSaved: %s\n', mat_path);

%% ---- Write LaTeX (hung style) ----
tex_path = fullfile(tex_dir, 'fitting_l250_cube20.tex');
fid = fopen(tex_path, 'w');
fprintf(fid, '%% Auto-generated by fit_J_l250_cube20.m on %s\n', datestr(now));
fprintf(fid, '%% Style mirrors magnetic_sim/ANSYS/backup/hung/pdf/scripts/fitting_l250.tex but with cube ±%g µm (best fit)\n\n', half_xy*1e6);
fprintf(fid, '\\documentclass{article}\n');
fprintf(fid, '\\usepackage[utf8]{inputenc}\n');
fprintf(fid, '\\usepackage{booktabs}\n');
fprintf(fid, '\\usepackage{siunitx}\n');
fprintf(fid, '\\usepackage{colortbl}\n');
fprintf(fid, '\\usepackage{xcolor}\n');
fprintf(fid, '\\usepackage{amsmath}\n\n');
fprintf(fid, '\\begin{document}\n\n');

fprintf(fid, '\\begin{table}[htbp]\n\\centering\n');
fprintf(fid, '\\caption{Hung $l=250~\\si{\\micro\\metre}$ \\quad (fitting region: $\\pm$%g~\\si{\\micro\\metre})}\n', half_xy*1e6);
fprintf(fid, '\\label{tab:hung_l250_cube%g}\n\n', half_xy*1e6);

fprintf(fid, '\\vspace{0.5em}\n');
fprintf(fid, '\\[\n\\text{Error} = \\frac{\\text{RMSE}}{|\\mathbf{B}_{FEM}|} \\cdot 100\n\\]\n');
fprintf(fid, '\\vspace{0.5em}\n\n');

fprintf(fid, '\\begin{tabular}{c c S[table-format=3.1] S[table-format=3.1]}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, ' & & \\multicolumn{2}{c}{\\cellcolor{yellow!30}\\textbf{Hung (Error=%.2f\\%%)}} \\\\\n', 100*err_mean);
fprintf(fid, '\\cmidrule(lr){3-4}\n');
fprintf(fid, 'Pole & & {$|\\ell|$ [\\si{\\micro\\metre}]} & {Tip$\\to$Charge [\\si{\\micro\\metre}]} \\\\\n');
fprintf(fid, '\\midrule\n');
for k = 1:N_POLES
    fprintf(fid, 'P%d & %s & %.1f & %.1f \\\\\n', k, layer_lab{k}, ell_um(k), tip2chg(k));
end
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Lower &       & %.1f & %.1f \\\\\n', mean_lower_ell, mean_lower_t2c);
fprintf(fid, 'Upper &       & %.1f & %.1f \\\\\n', mean_upper_ell, mean_upper_t2c);
fprintf(fid, '\\midrule\n');
fprintf(fid, '$R_a$ (Lower) & & \\multicolumn{2}{c}{$%.2f \\times 10^{9}$\\,A/Wb} \\\\\n', Ra_lower/1e9);
fprintf(fid, '$R_a$ (Upper) & & \\multicolumn{2}{c}{$%.2f \\times 10^{9}$\\,A/Wb} \\\\\n', Ra_upper/1e9);
fprintf(fid, '\\bottomrule\n\\end{tabular}\n\n');

fprintf(fid, '\\vspace{0.5em}\n\\small\n');
fprintf(fid, 'Tip$\\to$Origin = %g~\\si{\\micro\\metre} \\hfill Tip$\\to$Charge = $|\\ell|$ $-$ %g\n\n', ...
    TIP_TO_ORIG, TIP_TO_ORIG);
fprintf(fid, '\\end{table}\n\n');
fprintf(fid, '\\end{document}\n');
fclose(fid);
fprintf('Saved LaTeX: %s\n', tex_path);


%% ============== Helpers ==============
function [c, Ck] = cjoint(x, cd, km, N_POLES)
    p = reshape(x, 3, N_POLES);
    c = 0; Ck = zeros(N_POLES, 1);
    for k = 1:N_POLES
        pw = [cd(k).px, cd(k).py, cd(k).pz];
        bu = evcf(p, cd(k).KI_w, km, pw, N_POLES);
        Ck(k) = (bu' * cd(k).b_fem) / (bu' * bu);
        r = Ck(k)*bu - cd(k).b_fem;
        c = c + sum(r.^2);
    end
end

function b = evcf(p, w, km, pw, N_POLES)
    N = size(pw, 1);
    bx = zeros(N, 1); by = bx; bz = bx;
    for i = 1:N_POLES
        dx = pw(:,1) - p(1,i);
        dy = pw(:,2) - p(2,i);
        dz = pw(:,3) - p(3,i);
        r3 = (dx.^2 + dy.^2 + dz.^2).^(3/2);
        bx = bx + (-w(i)) * dx ./ r3;
        by = by + (-w(i)) * dy ./ r3;
        bz = bz + (-w(i)) * dz ./ r3;
    end
    b = km * [bx; by; bz];
end
