%% emit_gV.m -- 輸出 g_V = (6/5)·d11 = (6/5)·D(1,1)（Hall D 矩陣 gauge 增益；18-param bias 版）
% =========================================================================
% g_V = (6/5)·d11，d11 = D(1,1)（Hall D 矩陣的 (1,1)）。
% 來自 gauge D̄ = D·5/(6·D₁₁)：D = (6/5·D₁₁)·D̄ = g_V·D̄，故 g_V = (6/5)·D(1,1)。
% 純讀 calib_D_<variant>.mat 的 Dmat，算純量，出小 PDF。
% =========================================================================
clear; clc;
VARIANT = 'gap200um_mueq';
TREE = ['G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\' ...
        'long2016_hexapole_halfcut\Calibration_using_FEM_modeling\Hall_sensor_base_no_fix_dir'];
out_dir = fullfile(TREE,'results');

H = load(fullfile(TREE,'data',sprintf('calib_D_%s.mat',VARIANT)));   % Dmat
d11 = H.Dmat(1,1);
g_V = (6/5) * d11;
fprintf('d11 = D(1,1) = %.6e ；g_V = (6/5)·d11 = %.6e（無單位增益）\n', d11, g_V);

%% ---- xelatex PDF ----------------------------------------------------------
tex_path = fullfile(out_dir, sprintf('gV_%s.tex', VARIANT));
pdf_path = fullfile(out_dir, sprintf('gV_%s.pdf', VARIANT));
fid = fopen(tex_path,'w');
fprintf(fid,'%% Auto-generated by emit_gV.m\n');
fprintf(fid,'\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\begin{document}\n');
fprintf(fid,'\\[\n g_V = %.4f\\times10^{-3}.\n\\]\n', g_V*1e3);
fprintf(fid,'\\end{document}\n'); fclose(fid);

xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
old=cd(out_dir); [st,so]=system(sprintf('"%s" -interaction=nonstopmode -halt-on-error "%s"',xelatex,tex_path)); cd(old);
if st~=0 || ~exist(pdf_path,'file'); fprintf('%s\n',so); error('xelatex 編譯失敗'); end
for e={'.tex','.aux','.log','.out'}, f=fullfile(out_dir,sprintf('gV_%s%s',VARIANT,e{1})); if exist(f,'file'); delete(f); end, end
fprintf('已存 %s\n', pdf_path);
