%% main_Vmat.m -- 輸出 sensor 電壓矩陣 V 與 V^T(VV^T)^-1（修正 sensor 位置 + 100 點內插）
% =========================================================================
%  用「修正後的 6 顆 sensor 位置」(build_sensor_geometry，下極 −β 底錐面版) 與
%  「100 點圓柱內插平均」(extract_Vmat_interp) 算 sensor 電壓矩陣 Vmat，並輸出：
%    (1) V                       —— sensor 電壓矩陣（6×6）
%    (2) V^T (V V^T)^-1          —— 右擬逆（D = D^v · V^T(VV^T)^-1 用到的那塊）
%  PDF -> results/。（不輸出 sensor 位置表。）
%
%  變體 = gap200um_mueq（graded 場 + 修正位置的 graded sensor-local CSV）。
%  Vmat 與 main_Dmatrix 內的 V 相同（同一條 extract_Vmat_interp）。
%
%  REUSES：build_sensor_geometry、extract_Vmat_interp（+ 本檔 emit_labeled_matrix，沿用 main_Dmatrix）。
%  Current : I = 1 A = FEM 激發。Sign : all-source（翻下極 P1/P3/P6）。
% =========================================================================

clear; clc;

%% ---- config ----------------------------------------------------------------
VARIANT    = 'gap200um_mueq';  % FEM 場變體（graded 2 段式 μ_eff）
S_hall     = 130;              % Hall 靈敏度 [V/T]（EQ-730L）
n_uniform  = 10000;            % sensor 圓柱內均勻取樣點數（內插平均；2026-06-30 定案 10k）
SOFF_UPPER = 4.572e-3;         % [ADDED] 上極 sensor 沿錐面距極尖 [m]：canonical=4.572e-3（預設）；設 5.072e-3 = 沿斜面外移 0.5mm 的 what-if（檔名加 _upper5072、不蓋原版；只動上極，下極固定 4.572）
sofftag    = '';  if abs(SOFF_UPPER-4.572e-3)>1e-9, sofftag = sprintf('_upper%d', round(SOFF_UPPER*1e6)); end  % ≠canonical → 檔名加後綴、不蓋原版

%% ---- paths（沿用，不另寫）-------------------------------------------------
CAL  = ['G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\' ...
        'long2016_hexapole_halfcut\Calibration_using_FEM_modeling'];
addpath('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\backup\hexapole-long2016\analysis');  % mt_constants/import_ansys_data/filter_iron_nodes
addpath(fullfile(CAL,'Hall_sensor_base_fix_dir','code','function'));                            % build_sensor_geometry/extract_Vmat_interp
results_root = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\ANSYS_data\long2016_hexapole_halfcut\data';
mesh_csv_dir = fullfile(results_root,'mesh','graded','csv');   % graded sensor-local tet CSV（修正位置、csv/ 子夾）
TREE         = fullfile(CAL,'Hall_sensor_base_fix_dir');
out_dir      = fullfile(TREE,'results');   if ~exist(out_dir,'dir'); mkdir(out_dir); end
mat_dir      = fullfile(TREE,'data');      if ~exist(mat_dir,'dir'); mkdir(mat_dir); end

%% ---- 常數 + 慣例 -----------------------------------------------------------
cnst = mt_constants();
apdl_to_paper_idx = [1,3,6,5,2,4];

%% ---- 修正後 sensor 位置/法線（仍需，用來抽 Vmat；位置不輸出成結果）---------
[sensor_pos, sensor_n] = build_sensor_geometry(cnst, SOFF_UPPER);   % 3×6（WP 框 [m]，下極 −β；上極 SOFF=SOFF_UPPER）

%% ---- sensor 電壓 Vmat（gap200、graded csv、內插 100 點、all-source）---------
[Vmat, exc_sign] = extract_Vmat_interp(results_root, cnst, apdl_to_paper_idx, ...
                       sensor_pos, sensor_n, S_hall, mesh_csv_dir, n_uniform, [], [], VARIANT);

%% ---- 欄重排成 paper P1..P6（對角=自激發）+ 右擬逆 V^T(VV^T)^-1 --------------
[~, paper_to_apdl] = sort(apdl_to_paper_idx);   % = [1 5 2 6 4 3]
Vmat_p = Vmat(:, paper_to_apdl);                % 列=sensor P1..P6；欄=激發 P1..P6
Vrpinv = Vmat_p.' / (Vmat_p * Vmat_p.');        % V^T (V V^T)^-1：列=激發 P1..P6、欄=sensor P1..P6

%% ---- 印結果 ----------------------------------------------------------------
fprintf('\n=============== Hall-sensor V & V^T(VV^T)^-1（variant=%s, 內插 %d 點）===============\n', VARIANT, n_uniform);
fprintf('  V [V]（列=sensor P1..P6，欄=激發 P1..P6，對角=自激發）：\n');
for i=1:6, fprintf('   % .3e % .3e % .3e % .3e % .3e % .3e\n', Vmat_p(i,:)); end
fprintf('  V^T(VV^T)^-1 [1/V]（列=激發 P1..P6，欄=sensor P1..P6）：\n');
for i=1:6, fprintf('   % .4e % .4e % .4e % .4e % .4e % .4e\n', Vrpinv(i,:)); end
fprintf('========================================================================\n');

%% ---- 存 .mat 到本組 data/（規則#2）----------------------------------------
mat_out = fullfile(mat_dir, sprintf('calib_Vmat_%s%s.mat', VARIANT, sofftag));
save(mat_out, 'Vmat_p','Vrpinv','sensor_pos','sensor_n','exc_sign','VARIANT', ...
              'n_uniform','S_hall','apdl_to_paper_idx','paper_to_apdl');
fprintf('已存 %s\n', mat_out);

%% ---- 產生 xelatex PDF（V 與 V^T(VV^T)^-1）---------------------------------
pole     = {'P1','P2','P3','P4','P5','P6'};
tex_path = fullfile(out_dir, sprintf('Vmat_%s%s.tex', VARIANT, sofftag));
pdf_path = fullfile(out_dir, sprintf('Vmat_%s%s.pdf', VARIANT, sofftag));
fid = fopen(tex_path,'w');
fprintf(fid,'%% Auto-generated by main_Vmat.m — Hall-sensor V and V^T(VV^T)^-1 (P1..P6)\n');
fprintf(fid,'\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n');
fprintf(fid,'\\begin{document}\n');
fprintf(fid,['\\begin{center}\\large Hall-sensor $V$ and $V^{\\top}(VV^{\\top})^{-1}$' ...
             '\\quad(variant: %s;\\ %d-pt interp)\\end{center}\n\n'], strrep(VARIANT,'_','\_'), n_uniform);
emit_labeled_matrix(fid, 'V', Vmat_p, pole, pole, 'auto', ...
    'row $i$ = sensor pole P$i$;\ column $j$ = excited pole P$j$ (diagonal = self-excitation);\ units V.');
emit_labeled_matrix(fid, 'V^{\top}(VV^{\top})^{-1}', Vrpinv, pole, pole, 'auto', ...
    'row $i$ = excited pole P$i$;\ column $j$ = sensor pole P$j$;\ appears in $D = D^{v}\,V^{\top}(VV^{\top})^{-1}$;\ units 1/V.');
fprintf(fid,['\\noindent\\small Order P1--P6;\\ $I=1$\\,A (= FEM excitation);\\ all-source (flip-sink);\\ ' ...
             '$S_{\\mathrm{hall}}=%g$\\,V/T;\\ %d-point cylinder interpolation average;\\ ' ...
             'upper-pole sensor along-cone offset $=%.3f$\\,mm (lower $=4.572$\\,mm).\n'], S_hall, n_uniform, SOFF_UPPER*1e3);
fprintf(fid,'\\end{document}\n');
fclose(fid);

xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
old = cd(out_dir);
[st, sysout] = system(sprintf('"%s" -interaction=nonstopmode -halt-on-error "%s"', xelatex, tex_path));
cd(old);
if st ~= 0 || ~exist(pdf_path,'file'); fprintf('%s\n', sysout); error('xelatex 編譯失敗（見上方輸出）。'); end
for ext = {'.tex','.aux','.log','.out'}    % results 只留 .pdf
    f = fullfile(out_dir, sprintf('Vmat_%s%s%s', VARIANT, sofftag, ext{1})); if exist(f,'file'); delete(f); end
end
fprintf('已存 %s\n', pdf_path);

%% ---- local：渲染帶 P1..P6 表頭的 6×6 矩陣（含自動 10^n 因子；沿用 main_Dmatrix）----
function emit_labeled_matrix(fid, name_tex, M, rowlab, collab, factor_mode, caption)
    if strcmp(factor_mode,'auto')
        mx = max(abs(M(:)));
        if mx > 0, e = floor(log10(mx)); else, e = 0; end
        if e ~= 0, Ms = M / 10^e; fac = sprintf('10^{%d}\\,', e);
        else,      Ms = M;        fac = '';
        end
    else
        Ms = M; fac = '';
    end
    fprintf(fid,'\\[\n%s = %s\\begin{array}{c|cccccc}\n', name_tex, fac);
    fprintf(fid,' ');
    for j = 1:6, fprintf(fid,'& %s ', collab{j}); end
    fprintf(fid,'\\\\\\hline\n');
    for i = 1:6
        fprintf(fid,'%s ', rowlab{i});
        for j = 1:6, fprintf(fid,'& %+9.4f ', Ms(i,j)); end
        fprintf(fid,'\\\\\n');
    end
    fprintf(fid,'\\end{array}\n\\]\n');
    fprintf(fid,'\\noindent\\small %s\n\n', caption);
end
