%% emit_gV.m -- 輸出 ^Bĝ_V = (6/5)·h11 = (6/5)·Ĥ_V(1,1)（Hall 電壓側 gauge 增益）
% =========================================================================
% ^Bĝ_V = (6/5)·h11，h11 = Ĥ_V(1,1)（Hall Ĥ_V 矩陣的 (1,1)）。
% 來自 gauge D̄ = Ĥ_V·5/(6·h11)：Ĥ_V = (6/5·h11)·D̄ = ^Bĝ_V·D̄，故 ^Bĝ_V = (6/5)·Ĥ_V(1,1)。
% 純讀 calib_D_<variant>.mat 的 Dmat（= Ĥ_V，.mat field 名沿用），算純量，出小 PDF。
% =========================================================================
clear; clc;
VARIANT = 'gap200um_mueq';
TREE = ['G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\' ...
        'long2016_hexapole_halfcut\Calibration_using_FEM_modeling\Hall_sensor_base_fix_dir'];
out_dir = fullfile(TREE,'results');

H = load(fullfile(TREE,'data',sprintf('calib_D_%s.mat',VARIANT)));   % Dmat (= Ĥ_V)
h11 = H.Dmat(1,1);                  % Ĥ_V(1,1)（.mat field 'Dmat' 沿用）
ghat_V_B = (6/5) * h11;             % ^Bĝ_V（電壓側增益 T/V）
fprintf('h11 = Hhat_V(1,1) = %.6e ；^Bg_V = (6/5)*h11 = %.6e (T/V)\n', h11, ghat_V_B);

%% ---- xelatex PDF ----------------------------------------------------------
tex_path = fullfile(out_dir, sprintf('gV_%s.tex', VARIANT));
pdf_path = fullfile(out_dir, sprintf('gV_%s.pdf', VARIANT));
fid = fopen(tex_path,'w');
fprintf(fid,'%% Auto-generated by emit_gV.m\n');
fprintf(fid,'\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\begin{document}\n');
fprintf(fid,'\\[\n {}^{B}\\hat{g}_{V} = %.4f\\times10^{-3}.\n\\]\n', ghat_V_B*1e3);
fprintf(fid,'\\end{document}\n'); fclose(fid);

xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
old=cd(out_dir); [st,so]=system(sprintf('"%s" -interaction=nonstopmode -halt-on-error "%s"',xelatex,tex_path)); cd(old);
if st~=0 || ~exist(pdf_path,'file'); fprintf('%s\n',so); error('xelatex 編譯失敗'); end
for e={'.tex','.aux','.log','.out'}, f=fullfile(out_dir,sprintf('gV_%s%s',VARIANT,e{1})); if exist(f,'file'); delete(f); end, end
fprintf('已存 %s\n', pdf_path);
