%% emit_V_normalized_pct.m -- fix_dir V 矩陣「每欄除以自己對角」正規化 → 百分比(取絕對值) PDF
% =========================================================================
% 取 Hall_sensor_base_fix_dir 的 V（calib_D_<variant>.mat 的 Vmat_p），
% 每一欄除以該欄對角(自激發)再 ×100%、**取絕對值(去負號)** → Vn(i,j)=|V(i,j)/V(j,j)|*100。
% 對角=100%（自激發基準），off-diag = 各 sensor 相對該欄自激發的百分比大小（magnitude，無正負）。
% 輸出 PDF → Hall_sensor_base_fix_dir/results/V_normalized_pct_<variant>.pdf。
% =========================================================================
clear; clc;
VARIANT = 'gap200um_mueq';
TREE = ['G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\' ...
        'long2016_hexapole_halfcut\Calibration_using_FEM_modeling\Hall_sensor_base_fix_dir'];
out_dir = fullfile(TREE,'results');

H = load(fullfile(TREE,'data',sprintf('calib_D_%s.mat',VARIANT)));   % Vmat_p（列=sensor P1..P6、欄=激發 P1..P6）
V = H.Vmat_p;
Vn = abs(V ./ diag(V).') * 100;                     % 每欄除自己對角 ×100、取絕對值（去負號；對角=100）

fprintf('V 正規化(%%, abs)（每欄 ÷ 自對角 ×100、去負號；列=sensor，欄=激發）：\n');
for i=1:6, fprintf('  %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f\n', Vn(i,:)); end

%% ---- xelatex PDF ----------------------------------------------------------
pole = {'P1','P2','P3','P4','P5','P6'};
tex_path = fullfile(out_dir, sprintf('V_normalized_pct_%s.tex', VARIANT));
pdf_path = fullfile(out_dir, sprintf('V_normalized_pct_%s.pdf', VARIANT));
fid = fopen(tex_path,'w');
fprintf(fid,'%% Auto-generated by emit_V_normalized_pct.m\n');
fprintf(fid,'\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\begin{document}\n');
fprintf(fid,'\\begin{center}\\large Hall-sensor $V$ — per-column normalized (\\%%, magnitude)\\quad(variant: %s)\\end{center}\n\n', strrep(VARIANT,'_','\_'));
fprintf(fid,'\\[\n\\tilde{V}\\;[\\%%] = \\begin{array}{c|cccccc}\n ');
for j=1:6, fprintf(fid,'& %s ',pole{j}); end
fprintf(fid,'\\\\\\hline\n');
for i=1:6, fprintf(fid,'%s ',pole{i}); for j=1:6, fprintf(fid,'& %8.2f ',Vn(i,j)); end, fprintf(fid,'\\\\\n'); end
fprintf(fid,'\\end{array}\n\\]\n');
fprintf(fid,['\\noindent\\small $\\tilde{V}_{ij}=|V_{ij}/V_{jj}|\\times100\\%%$ (each column divided by its own diagonal, magnitude);\\ ' ...
             'row $i$ = sensor pole P$i$;\\ column $j$ = excited pole P$j$;\\ diagonal $=100\\%%$ (self-excitation reference);\\ ' ...
             'off-diagonal = each sensor as \\%% of that column''s self-excitation signal (sign removed).\n']);
fprintf(fid,'\\end{document}\n'); fclose(fid);

xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
old=cd(out_dir); [st,so]=system(sprintf('"%s" -interaction=nonstopmode -halt-on-error "%s"',xelatex,tex_path)); cd(old);
if st~=0 || ~exist(pdf_path,'file'); fprintf('%s\n',so); error('xelatex 編譯失敗'); end
for e={'.tex','.aux','.log','.out'}, f=fullfile(out_dir,sprintf('V_normalized_pct_%s%s',VARIANT,e{1})); if exist(f,'file'); delete(f); end, end
fprintf('已存 %s\n', pdf_path);
