%% main_singlepole.m -- single-pole (P1) no-bias point-charge fit {ell, ghat_I}
%  單極退化：無 K_bar、增益塌成純量 ghat_I、電流 I 純量。
%  模型：B(p) = ghat_I * I * (p/ell - dhat)/|p/ell - dhat|^3   （電荷在軸 ell*dhat，無 bias）
%  3 形狀（filled / halfcut / tipcut）各 fit 一組 {ell, ghat_I}；取樣 R<=150µm 球（WP 為心）。
%  +x mesh：極軸=+x、WP 在原點、d_hat=[1 0 0]，資料免 R_act 旋轉、免 z-shift。
%  誤差逐點相減（B_model - B_FEM）→ cost J = Σ|r|²。
%  all-source：coil 電流在 mesh 已翻向 → raw FEM 即 source（Bx@WP<0）→ SGN=+1 不再翻。
%  ⚠ 單極只 1 致動自由度 → K_bar 消失、ghat_I=G/I（G,I 皆 1x1）、不算 C/κ。
%  輸出：results/singlepole_fit.pdf（表格：ell、ghat_I、cost J）。無直方圖。

clear; clc;

%% ---- config ----
GROUP  = 'shapes';    % [ADDED] 'shapes' = filled/halfcut/tipcut（尖端形狀）；
                      %          'gap_pos' = 支撐座氣隙同截面積(100mm²)不同位置 x42.5/47.5
switch GROUP
    case 'shapes'                                   % 3 形狀（原預設）
        SHAPES   = {'filled','halfcut','tipcut'};   % 子夾名
        LABELS   = {'filled','halfcut','tipcut'};   % PDF/表列名
        BASENAME = 'singlepole_fit';
    case 'gap_pos'                                  % [ADDED] 同面積不同位置氣隙對
        SHAPES   = {'filled_gap_x42p5','filled_gap_x47p5'};
        LABELS   = {'x=42.5 mm','x=47.5 mm'};
        BASENAME = 'singlepole_gap_pos';
    otherwise, error('GROUP must be ''shapes'' or ''gap_pos''.');
end
R_fit  = 150e-6;      % 取樣半徑 [m]（使用者拍板 R<=150µm：點單極有效區內、ĝ_I 貼近物理中心場）
I      = 1;           % drive current [A] = FEM 激發（fit-current-matches-sim）

%% ---- paths ----
TREE = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\Calibration_using_FEM_modeling\fix_dir';
addpath('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\backup\hexapole-long2016\analysis');   % mt_constants
addpath(fullfile(TREE,'code','main_function'));                                                 % load_singlepole / fit_singlepole
DATA = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\ANSYS_data\long2016_hexapole_halfcut\data\coil1\singlepole';
resdir = fullfile(TREE,'results');   if ~exist(resdir,'dir'); mkdir(resdir); end

%% ---- constants + frame (+x mesh: pole axis = +x, WP at ORIGIN; coil1 -> P1) ----
cnst = mt_constants();
cnst.SPH_OFST = 0;                                  % [MODIFIED] +x mesh: WP at ORIGIN (no z-shift)
d_act = [1; 0; 0];                                  % [MODIFIED] +x mesh: pole axis +x, tip at (500,0,0)um
SGN   = +1;                                         % [MODIFIED] FEM Bx@WP<0 (median ~-1.7mT) = already source
                                                    %   (coil current flipped in mesh deck) -> no flip -> ghat_I>0
fprintf('d_act (P1 axis) = [%.0f %.0f %.0f], SGN=%+d (raw FEM already source)\n', d_act, SGN);

%% ---- fit each shape ----
ns = numel(SHAPES);
ell_um = zeros(1,ns); gI = zeros(1,ns); Jcost = zeros(1,ns); Nnode = zeros(1,ns);
for s = 1:ns
    [Pw, BmT] = load_singlepole(fullfile(DATA, SHAPES{s}), cnst, 'tip');   % R<2mm ball @ WP
    Pa = Pw;                                         % [MODIFIED] data already +x/WP-origin frame (no R_act)
    Ba = SGN * BmT;                                  % [MODIFIED] all-source (SGN=+1: raw already source)
    in = vecnorm(Pa,2,2) <= R_fit;  Pa = Pa(in,:);  Ba = Ba(in,:);
    Nnode(s) = size(Pa,1);
    [ell, g, J] = fit_singlepole(Pa, Ba, d_act, I);
    ell_um(s) = ell*1e6;  gI(s) = g;  Jcost(s) = J;
    fprintf('%-8s | N(R150)=%5d | ell=%.2f um | ghat_I=%.4f mT/A | cost J=%.4g mT^2\n', ...
            SHAPES{s}, Nnode(s), ell_um(s), gI(s), Jcost(s));
end

%% ---- 存 fit 結果 .mat（供 side-view quiver 標 charge 位置）----
datadir = fullfile(TREE,'data');  if ~exist(datadir,'dir'); mkdir(datadir); end
save(fullfile(datadir,[BASENAME '.mat']), 'GROUP','SHAPES','LABELS','ell_um','gI','Jcost','Nnode','R_fit','I');

%% ---- 輸出 PDF（無直方圖；.tex -> xelatex -> 只留 .pdf） ----
emit_singlepole_pdf(LABELS, ell_um, gI, Jcost, Nnode, R_fit, I, resdir, BASENAME);

%% ================= local functions =================
function emit_singlepole_pdf(shapes, ell_um, gI, Jcost, Nnode, R_fit, I, out_dir, basename)
    tex_path = fullfile(out_dir, [basename '.tex']);
    pdf_path = fullfile(out_dir, [basename '.pdf']);
    fid = fopen(tex_path, 'w');
    fprintf(fid, '%% Auto-generated by main_singlepole.m\n');
    fprintf(fid, '\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\begin{document}\n');
    fprintf(fid, '\\begin{center}\\large\\textbf{Single-pole (P1) no-bias point-charge fit}\\end{center}\n');
    fprintf(fid, '\\[\n B(p) = \\hat{g}_I\\, I\\, \\dfrac{p/\\hat{\\ell} - \\hat{d}}{|p/\\hat{\\ell} - \\hat{d}|^{3}}, \\quad R\\le %d~\\mu\\mathrm{m}, \\quad I=%g~\\mathrm{A}\n\\]\n', round(R_fit*1e6), I);
    fprintf(fid, '\\begin{center}\n\\begin{tabular}{lcccc}\n\\hline\n');
    fprintf(fid, 'case & $\\hat{\\ell}~[\\mu\\mathrm{m}]$ & ${}^{B}\\hat{g}_{I}~[\\mathrm{mT/A}]$ & $J=\\sum|B_{\\mathrm{mod}}-B_{\\mathrm{FEM}}|^{2}~[\\mathrm{mT}^{2}]$ & $N$ \\\\\n\\hline\n');
    for s = 1:numel(shapes)
        fprintf(fid, '%s & %.2f & %.4f & %.4g & %d \\\\\n', shapes{s}, ell_um(s), gI(s), Jcost(s), Nnode(s));
    end
    fprintf(fid, '\\hline\n\\end{tabular}\n\\end{center}\n');
    fprintf(fid, '\\noindent\\small residual $B_{\\mathrm{mod}}-B_{\\mathrm{FEM}}$ per real FEM node in the actuator frame; $J$ = lsqnonlin cost. Single pole = 1 actuation DOF (no $\\mathcal{C}/\\kappa$).\n');
    fprintf(fid, '\\end{document}\n');
    fclose(fid);
    xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
    [st, so] = system(sprintf('"%s" -interaction=nonstopmode -halt-on-error -output-directory="%s" "%s"', xelatex, out_dir, tex_path));
    if st~=0 || ~exist(pdf_path,'file'); fprintf('%s\n', so); error('xelatex 編譯失敗'); end
    for e = {'.tex','.aux','.log','.out'}
        f = fullfile(out_dir, [basename e{1}]);  if exist(f,'file'); delete(f); end
    end
    fprintf('已存 %s\n', pdf_path);
end
