%% gen_KI_latex.m — emit charge-model fit RESULTS as LaTeX (for Overleaf)
%  Reads fit_KI_full.mat, writes fit_KI_cube40.tex (results only).
clear; clc;
matfile = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\fit_KI_full.mat';
S = load(matfile);
texdir  = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\charge_model_fitting\long2016_hexapole_halfcut\scripts';
texfile = fullfile(texdir, sprintf('fit_KI_cube%.0f.tex', S.cube_half*1e6));

% Presentation convention: show every excited pole as a SOURCE. Upper poles
% (P2,P4,P5) coil columns flipped so all diagonals are positive (emit) and all
% off-diagonals negative (receive). The fit (.mat) is NOT changed.
Khat = S.Khat;
Khat(:, [2 4 5]) = -Khat(:, [2 4 5]);

fid = fopen(texfile, 'w');
fprintf(fid, '%% Auto-generated by gen_KI_latex.m -- charge-model fit results\n');
fprintf(fid, '\\documentclass{article}\n\\usepackage{amsmath}\n\\begin{document}\n\n');

fprintf(fid, 'Fitting (sampling) region: cube $|x|,|y|,|z| \\le %.0f\\,\\mu\\mathrm{m}$ about the working point (WP).\n\n', ...
        S.cube_half*1e6);
fprintf(fid, 'Sign convention: every excited pole shown as a source (upper-pole P2, P4, P5 coil columns flipped), so all diagonal entries are positive (emit) and all off-diagonal entries negative (receive).\n\n');

fprintf(fid, '\\[\n\\widehat{\\mathbf{K}}_I^{\\mathrm{FEM}} =\n\\begin{bmatrix}\n');
for i = 1:6
    fprintf(fid, '%.4f', Khat(i,1));
    for j = 2:6, fprintf(fid, ' & %.4f', Khat(i,j)); end
    if i < 6, fprintf(fid, ' \\\\\n'); else, fprintf(fid, '\n'); end
end
fprintf(fid, '\\end{bmatrix}\n\\]\n\n');

fprintf(fid, '\\[\n');
fprintf(fid, '\\widehat{\\ell} = %.3f~\\mathrm{mm}, \\qquad ', S.ell*1e3);
fprintf(fid, '\\widehat{g}_B = %s, \\qquad ', sci(S.gB));
fprintf(fid, 'k_{11} = \\tfrac{5}{6}, \\qquad ');
fprintf(fid, '\\mathcal{R}_a = %s~\\mathrm{A/Wb}.\n', sci(S.R_a));
fprintf(fid, '\\]\n\n\\end{document}\n');
fclose(fid);
fprintf('wrote %s\n', texfile);

%% ---- second output: the THREE fitted quantities only (no k11, no R_a) ----
texfile3 = fullfile(texdir, sprintf('fit_KI_cube%.0f_fit3.tex', S.cube_half*1e6));
fid = fopen(texfile3, 'w');
fprintf(fid, '%% Auto-generated by gen_KI_latex.m -- three fitted quantities only\n');
fprintf(fid, '\\documentclass{article}\n\\usepackage{amsmath}\n\\begin{document}\n\n');
fprintf(fid, 'Fitting (sampling) region: cube $|x|,|y|,|z| \\le %.0f\\,\\mu\\mathrm{m}$ about the working point (WP).\n\n', ...
        S.cube_half*1e6);
fprintf(fid, 'Sign convention: every excited pole shown as a source (upper-pole P2, P4, P5 coil columns flipped), so all diagonal entries are positive (emit) and all off-diagonal entries negative (receive).\n\n');
fprintf(fid, '\\[\n\\widehat{\\mathbf{K}}_I^{\\mathrm{FEM}} =\n\\begin{bmatrix}\n');
for i = 1:6
    fprintf(fid, '%.4f', Khat(i,1));
    for j = 2:6, fprintf(fid, ' & %.4f', Khat(i,j)); end
    if i < 6, fprintf(fid, ' \\\\\n'); else, fprintf(fid, '\n'); end
end
fprintf(fid, '\\end{bmatrix}\n\\]\n\n');
fprintf(fid, '\\[\n\\widehat{\\ell} = %.3f~\\mathrm{mm}, \\qquad \\widehat{g}_B = %s.\n\\]\n\n', ...
        S.ell*1e3, sci(S.gB));
fprintf(fid, '\\end{document}\n');
fclose(fid);
fprintf('wrote %s\n', texfile3);

function s = sci(x)
    if x == 0, s = '0'; return; end
    e = floor(log10(abs(x)));
    s = sprintf('%.3f\\times10^{%d}', x/10^e, e);
end
