function gen_KI_ball_latex(Rum)
%% gen_KI_ball_latex(Rum)
%  Emit the R=<Rum>um charge-model fit result (new graded ALL-SOURCE data, gB0=50) as
%  LaTeX -> fit_KI_R<Rum>.tex. Parameterised version of gen_KI_R040_latex.m.
%  Reads KI_convergence_gB50.mat, recomputes the per-point fitting error on the SAME
%  fit sample (Neq pts/coil), and writes raw Khat + ell + gB + Error.
%  Error = (1/N) sum_i |B_model_i - B_FEM_i|/|B_FEM_i| * 100   (per-point, equal weight).
    if nargin < 1, Rum = 100; end
    addpath('G:\my_workspace\code\FEM_sim\magnetic_sim\hexapole-long2016\analysis');
    dir_P1     = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\ANSYS_data\long2016_hexapole_halfcut\coil1\graded';
    dir_P2toP6 = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\ANSYS_data\long2016_hexapole_halfcut\coil2\graded';
    texdir     = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\charge_model_fitting\long2016_hexapole_halfcut\scripts';
    S = load('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\fit_KI_ball\KI_convergence_gB50.mat');

    R  = Rum*1e-6;
    ri = find(round(S.R_list*1e6)==Rum,1);  assert(~isempty(ri),'R=%dum not in fit',Rum);
    f  = S.fitP(ri);  Khat = f.Khat;  Neq = S.Neq;  I = S.I_actual;
    cnst = mt_constants();  apdl_to_paper_idx = [1 3 6 5 2 4];
    tip = [cnst.pole_tip_x; cnst.pole_tip_y; cnst.pole_tip_z_wp];  dhat = tip ./ vecnorm(tip);

    %% recompute per-point error on the SAME fit sample (Neq/coil, rng0)
    err = [];
    for k = 1:6
        cname = sprintf('coil%d',k);  if k==1, rdir=dir_P1; else, rdir=dir_P2toP6; end
        d = import_ansys_data(rdir,'wp',cname);
        air = filter_iron_nodes(d.x,d.y,d.z,cnst,struct('visualize',false));
        P = [d.x(air), d.y(air), d.z(air)-cnst.SPH_OFST];  Bn = +[d.bx(air),d.by(air),d.bz(air)];
        idx = find(sum(P.^2,2) < R^2);  rng(0); idx = idx(randperm(numel(idx),Neq));
        p = P(idx,:);  Bfem = Bn(idx,:);
        pn = p/f.ell;  w = f.gB * Khat(:,apdl_to_paper_idx(k)) * I;  Bmod = zeros(size(p));
        for i=1:6, dd = pn - dhat(:,i).'; r3 = vecnorm(dd,2,2).^3; Bmod = Bmod + w(i)*dd./r3; end
        err = [err; vecnorm(Bmod-Bfem,2,2)./vecnorm(Bfem,2,2)*100]; %#ok<AGROW>
    end
    mE = mean(err);  medE = median(err);  maxE = max(err);  npts = 6*Neq;

    %% write tex
    texfile = fullfile(texdir, sprintf('fit_KI_R%03d.tex', Rum));
    fid = fopen(texfile,'w');
    fprintf(fid, '%% Auto-generated by gen_KI_ball_latex.m -- charge-model fit, ball R=%d um (new graded all-source data, gB0=50)\n', Rum);
    fprintf(fid, '\\documentclass{article}\n\\usepackage{amsmath}\n\\begin{document}\n\n');
    fprintf(fid, 'Fitting (sampling) region: ball $\\lVert\\mathbf{p}\\rVert \\le %d\\,\\mu\\mathrm{m}$ about the working point (WP); %d sample nodes (%d per coil $\\times$ 6 coils, equal across shells).\n\n', Rum, npts, Neq);
    fprintf(fid, 'Data: graded-mesh FEM, every excited pole simulated as a source at $1\\,\\mathrm{A}$. The fitted $\\widehat{\\mathbf{K}}_I^{\\mathrm{FEM}}$ is shown raw (source convention, no column flip). Initial guess $\\widehat{g}_B=50$; the cost reached its global minimum (verified by multistart).\n\n');
    fprintf(fid, '\\[\n\\widehat{\\mathbf{K}}_I^{\\mathrm{FEM}} =\n\\begin{bmatrix}\n');
    for i=1:6
        fprintf(fid,'%.4f',Khat(i,1)); for j=2:6, fprintf(fid,' & %.4f',Khat(i,j)); end
        if i<6, fprintf(fid,' \\\\\n'); else, fprintf(fid,'\n'); end
    end
    fprintf(fid, '\\end{bmatrix}\n\\]\n\n');
    fprintf(fid, '\\[\n\\widehat{\\ell} = %.3f~\\mathrm{mm}, \\qquad \\widehat{g}_B = %s.\n\\]\n\n', f.ell*1e3, sci(f.gB));
    fprintf(fid, 'Per-point fitting error over the region, $\\mathrm{Error}=\\dfrac{1}{N}\\sum_{i=1}^{N}\\dfrac{\\lvert\\mathbf{B}_{\\mathrm{model}}(\\mathbf{p}_i)-\\mathbf{B}_{\\mathrm{FEM}}(\\mathbf{p}_i)\\rvert}{\\lvert\\mathbf{B}_{\\mathrm{FEM}}(\\mathbf{p}_i)\\rvert}\\times100\\%%$ with $N=%d$ sample points:\n', npts);
    fprintf(fid, '\\[\n\\mathrm{Error} = %.2f\\%% \\quad(\\text{median } %.2f\\%%,\\ \\max %.2f\\%%).\n\\]\n\n', mE, medE, maxE);
    if any(diag(Khat) < 0)
        fprintf(fid, '\\emph{Note:} at this small radius the inverse problem is ill-conditioned, so the field error is low yet some $\\widehat{\\mathbf{K}}_I$ entries are non-physical (negative diagonal terms); the coupling matrix is well-determined only for larger shells ($\\gtrsim\\!200\\,\\mu\\mathrm{m}$).\n\n');
    else
        fprintf(fid, '\\emph{Note:} all diagonal entries are positive (physical, emit); the coupling matrix is best-determined around $R\\approx100\\text{--}300\\,\\mu\\mathrm{m}$.\n\n');
    end
    fprintf(fid, '\\end{document}\n');
    fclose(fid);
    fprintf('wrote %s  (ell=%.3f mm, gB=%.4e, Error=%.2f%%)\n', texfile, f.ell*1e3, f.gB, mE);
end

function s = sci(x)
    if x==0, s='0'; return; end
    e = floor(log10(abs(x)));  s = sprintf('%.3f\\times10^{%d}', x/10^e, e);
end
