%% gen_KI_R040_latex.m — emit the R=40 um charge-model fit result as LaTeX (Overleaf)
%  Reads the new graded all-source fit (KI_convergence_gB50.mat) and writes
%  fit_KI_R040.tex. Standalone amsmath, English.
%
%  NOTE on sign convention: the underlying FEM data is the NEW graded ALL-SOURCE
%  solve (every excited pole is a source; B is NOT negated in the fit). So the
%  fitted K_I^FEM already comes out in source convention and is shown RAW --
%  no upper-pole column flip (unlike the old sink-convention generator).
clear; clc;
matfile = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\fit_KI_ball\KI_convergence_gB50.mat';
texdir  = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\charge_model_fitting\long2016_hexapole_halfcut\scripts';
S = load(matfile);
E = load('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\fit_KI_ball\KI_perpoint_gB50_R040.mat');  % per-point error

Rtarget = 40e-6;                                  % <-- shell to emit
ri = find(round(S.R_list*1e6) == round(Rtarget*1e6), 1);
assert(~isempty(ri), 'R=%.0f um not in R_list', Rtarget*1e6);
f = S.fitP(ri);
Khat = f.Khat;                                    % RAW (no flip; data already all-source)

texfile = fullfile(texdir, sprintf('fit_KI_R%03.0f.tex', Rtarget*1e6));
fid = fopen(texfile, 'w');
fprintf(fid, '%% Auto-generated by gen_KI_R040_latex.m -- charge-model fit, ball R=%.0f um (new graded all-source data)\n', Rtarget*1e6);
fprintf(fid, '\\documentclass{article}\n\\usepackage{amsmath}\n\\begin{document}\n\n');

fprintf(fid, 'Fitting (sampling) region: ball $\\lVert\\mathbf{p}\\rVert \\le %.0f\\,\\mu\\mathrm{m}$ about the working point (WP); %d sample nodes (%d per coil $\\times$ 6 coils, equal across shells).\n\n', ...
        Rtarget*1e6, f.npts, f.npts/6);
fprintf(fid, 'Data: graded-mesh FEM, every excited pole simulated as a source at $1\\,\\mathrm{A}$. The fitted $\\widehat{\\mathbf{K}}_I^{\\mathrm{FEM}}$ is shown raw (source convention, no column flip). Initial guess $\\widehat{g}_B=50$; the cost reached its global minimum (verified by multistart).\n\n');

fprintf(fid, '\\[\n\\widehat{\\mathbf{K}}_I^{\\mathrm{FEM}} =\n\\begin{bmatrix}\n');
for i = 1:6
    fprintf(fid, '%.4f', Khat(i,1));
    for j = 2:6, fprintf(fid, ' & %.4f', Khat(i,j)); end
    if i < 6, fprintf(fid, ' \\\\\n'); else, fprintf(fid, '\n'); end
end
fprintf(fid, '\\end{bmatrix}\n\\]\n\n');

fprintf(fid, '\\[\n\\widehat{\\ell} = %.3f~\\mathrm{mm}, \\qquad \\widehat{g}_B = %s.\n\\]\n\n', ...
        f.ell*1e3, sci(f.gB));

fprintf(fid, 'Per-point fitting error over the region, $\\mathrm{Error}=\\dfrac{1}{N}\\sum_{i=1}^{N}\\dfrac{\\lvert\\mathbf{B}_{\\mathrm{model}}(\\mathbf{p}_i)-\\mathbf{B}_{\\mathrm{FEM}}(\\mathbf{p}_i)\\rvert}{\\lvert\\mathbf{B}_{\\mathrm{FEM}}(\\mathbf{p}_i)\\rvert}\\times100\\%%$ with $N=%d$ sample points:\n', f.npts);
fprintf(fid, '\\[\n\\mathrm{Error} = %.2f\\%% \\quad(\\text{median } %.2f\\%%,\\ \\max %.2f\\%%).\n\\]\n\n', ...
        E.meanPctErr, E.medPctErr, E.maxPctErr);

fprintf(fid, '\\emph{Note:} at this small radius the inverse problem is ill-conditioned (samples confined within $%.0f\\,\\mu\\mathrm{m}$ of the WP while the charges sit at $\\sim\\!500\\,\\mu\\mathrm{m}$), so the field error is very low yet several $\\widehat{\\mathbf{K}}_I$ entries are non-physical (negative diagonal terms); the coupling matrix is well-determined only for larger shells ($\\gtrsim\\!200\\,\\mu\\mathrm{m}$).\n\n', Rtarget*1e6);

fprintf(fid, '\\end{document}\n');
fclose(fid);
fprintf('wrote %s\n', texfile);

function s = sci(x)
    if x == 0, s = '0'; return; end
    e = floor(log10(abs(x)));
    s = sprintf('%.3f\\times10^{%d}', x/10^e, e);
end
