%% gen_fit_J_cube40_latex.m
%   Generate a LaTeX table for the [J] 6-charge joint fit of the Long Fei
%   halfcut hexapole (kuo V4 baseline, 6 coils x 0.6 A), cube +/-40 um.
%
%   Loads the fit result (joint_6coil_40um_fit.mat) and writes a standalone
%   LaTeX table in the same style as magnetic_sim/ANSYS/backup/hung/pdf/scripts/fitting_l250_cube20.tex.
%
%   Output:
%     magnetic_sim/ANSYS/main/doc/fitting_charge/long2016_hexapole_halfcut/scripts/fit_J_cube40.tex
%
%   Run from anywhere (absolute paths used).

clear; clc;

%% ---- Paths ----
mat_path = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\calibration\joint_6coil_40um_fit.mat';
tex_dir  = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\fitting_charge\long2016_hexapole_halfcut\scripts';
if ~exist(tex_dir, 'dir'); mkdir(tex_dir); end
tex_path = fullfile(tex_dir, 'fit_J_cube40.tex');

%% ---- Load fit ----
S = load(mat_path);
best      = S.best;
cnst      = S.cnst;
cube_half = S.cube_half;     % 40e-6
I_actual  = S.I_actual;      % 0.6
a2p       = S.apdl_to_paper_idx;   % [1 3 6 5 2 4]

%% ---- Per-pole stats (paper pole index i = 1..6) ----
ell_um   = zeros(1,6);
tip2o_um = zeros(1,6);   % tip-to-origin (WP) distance
t2c_um   = zeros(1,6);   % tip-to-charge
is_lower = logical(cnst.pole_is_lower);
layer    = cell(1,6);

for i = 1:6
    ell_um(i)   = norm(best.pos(:,i)) * 1e6;
    tip         = [cnst.pole_tip_x(i); cnst.pole_tip_y(i); cnst.pole_tip_z_wp(i)];
    tip2o_um(i) = norm(tip) * 1e6;
    t2c_um(i)   = ell_um(i) - tip2o_um(i);
    if is_lower(i), layer{i} = 'Lower'; else, layer{i} = 'Upper'; end
end

% R_a is stored per coil k; paper pole of coil k = a2p(k)
R_a_pole = zeros(1,6);
for k = 1:6
    R_a_pole(a2p(k)) = abs(best.R_a_k(k));   % magnitude (sign is coil winding convention)
end

lower_idx = find(is_lower);
upper_idx = find(~is_lower);
mean_lower_ell = mean(ell_um(lower_idx));
mean_upper_ell = mean(ell_um(upper_idx));
mean_lower_t2c = mean(t2c_um(lower_idx));
mean_upper_t2c = mean(t2c_um(upper_idx));
Ra_lower = mean(R_a_pole(lower_idx));
Ra_upper = mean(R_a_pole(upper_idx));
mean_tip2o = mean(tip2o_um);

%% ---- Console echo (sanity) ----
fprintf('===== [J] fit, cube +/-%.0f um, I = %.1f A =====\n', cube_half*1e6, I_actual);
fprintf('Mean error: %.2f%%\n', best.mean_err*100);
fprintf('Pole | Layer |  |ell| um | Tip->Charge | R_a [A/Wb]\n');
for i = 1:6
    fprintf(' P%d  | %-5s | %8.1f | %+8.1f   | %.3e\n', ...
        i, layer{i}, ell_um(i), t2c_um(i), R_a_pole(i));
end
fprintf('Lower mean |ell|=%.1f  t2c=%.1f  R_a=%.3e\n', mean_lower_ell, mean_lower_t2c, Ra_lower);
fprintf('Upper mean |ell|=%.1f  t2c=%.1f  R_a=%.3e\n', mean_upper_ell, mean_upper_t2c, Ra_upper);
fprintf('Tip->Origin (mean) = %.1f um\n', mean_tip2o);

%% ---- Write LaTeX (hung style) ----
fid = fopen(tex_path, 'w');
fprintf(fid, '%% Auto-generated by gen_fit_J_cube40_latex.m on %s\n', datestr(now));
fprintf(fid, '%% [J] 6-charge joint fit, Long Fei halfcut hexapole (kuo V4 baseline)\n');
fprintf(fid, '%% FEM: 6 coils x %.1f A, fit region cube +/-%g um\n\n', I_actual, cube_half*1e6);

fprintf(fid, '\\documentclass{article}\n');
% [MODIFIED] No siunitx — only booktabs/colortbl/xcolor/amsmath so it pastes
% [MODIFIED] into any Overleaf project (pdfLaTeX) without siunitx v3 quirks.
fprintf(fid, '\\usepackage[utf8]{inputenc}\n');
fprintf(fid, '\\usepackage{booktabs}\n');
fprintf(fid, '\\usepackage{colortbl}\n');
fprintf(fid, '\\usepackage{xcolor}\n');
fprintf(fid, '\\usepackage{amsmath}\n\n');
fprintf(fid, '\\begin{document}\n\n');

fprintf(fid, '\\begin{table}[htbp]\n\\centering\n');
fprintf(fid, ['\\caption{Long Fei halfcut hexapole --- [J] 6-charge joint fit ' ...
              '($I=%.1f$~A, fitting region: $\\pm %g~\\mu$m)}\n'], ...
              I_actual, cube_half*1e6);
fprintf(fid, '\\label{tab:longfei_halfcut_J_cube%g}\n\n', cube_half*1e6);

% [MODIFIED] Error in the form of Long 2016 Fig. 2.6(c): per-point error vector
% [MODIFIED] Delta B = B_fit - B_FEM, percent error = |Delta B| / |B_FEM| * 100.
fprintf(fid, '\\vspace{0.5em}\n');
fprintf(fid, ['\\[\n\\boldsymbol{\\Delta}\\mathbf{B} = \\mathbf{B}_{fit} - \\mathbf{B}_{\\mathrm{FEM}}, ' ...
              '\\qquad \\text{Error \\%%} = \\frac{\\lvert\\boldsymbol{\\Delta}\\mathbf{B}\\rvert}' ...
              '{\\lvert\\mathbf{B}_{\\mathrm{FEM}}\\rvert}\\cdot 100\n\\]\n']);
fprintf(fid, '\\vspace{0.5em}\n\n');

fprintf(fid, '\\begin{tabular}{c c r r}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, [' & & \\multicolumn{2}{c}{\\cellcolor{yellow!30}' ...
              '\\textbf{Long Fei halfcut (Error = %.2f\\%%)}} \\\\\n'], best.mean_err*100);
fprintf(fid, '\\cmidrule(lr){3-4}\n');
fprintf(fid, 'Pole & Layer & $|\\ell|$ [$\\mu$m] & Tip$\\to$Charge [$\\mu$m] \\\\\n');
fprintf(fid, '\\midrule\n');
for i = 1:6
    fprintf(fid, 'P%d & %s & %.1f & %.1f \\\\\n', i, layer{i}, ell_um(i), t2c_um(i));
end
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Lower & & %.1f & %.1f \\\\\n', mean_lower_ell, mean_lower_t2c);
fprintf(fid, 'Upper & & %.1f & %.1f \\\\\n', mean_upper_ell, mean_upper_t2c);
fprintf(fid, '\\midrule\n');
fprintf(fid, '$R_a$ (Lower) & & \\multicolumn{2}{c}{$%.2f \\times 10^{8}$ A/Wb} \\\\\n', Ra_lower/1e8);
fprintf(fid, '$R_a$ (Upper) & & \\multicolumn{2}{c}{$%.2f \\times 10^{8}$ A/Wb} \\\\\n', Ra_upper/1e8);
fprintf(fid, '\\bottomrule\n\\end{tabular}\n\n');

fprintf(fid, '\\vspace{0.5em}\n\\small\n');
fprintf(fid, ['Tip$\\to$Origin $\\approx %.0f~\\mu$m (tip-to-WP distance) ' ...
              '\\hfill Tip$\\to$Charge $= |\\ell| - $ Tip$\\to$Origin\n\n'], mean_tip2o);
fprintf(fid, '\\end{table}\n\n');
fprintf(fid, '\\end{document}\n');
fclose(fid);

fprintf('\nSaved LaTeX: %s\n', tex_path);
