%% compute_V_out_V_in_kA0p3.m — V_out/V_in matrix per bs_derivation.pdf
%
%  Strictly follows the derivation in
%      magnetic_sim/ANSYS/main/doc/Solve B_matrix/pdf/bs_derivation.pdf
%  (= magnetic_sim/ANSYS/main/doc/Solve B_matrix/scripts/bs_derivation.tex), no sign-convention
%  modification on top of the raw FEM matrix.
%
%  Derivation summary:
%      V_ij        = S_hall · B_ij                   (Hall voltage)
%      V_ij / I_in = (S_hall / I_in) · B̄_S  ≜ B_S    [V/A]
%      I_in        = V_in · k_A                       (amplifier)
%      V_out/V_in  = k_A · B_S = (k_A · S_hall / I_in) · B̄_S    [V/V]
%
%  Numerical plug-in (this script):
%      k_A    = 0.3       A/V    (Long Fei: 1 V input → 0.3 A output)
%      I_in   = 0.6       A      (test current)
%      S_hall = 0.130     V/mT  (= 130 V/T, Hall sensor sensitivity)
%      coef   = k_A · S_hall / I_in = 65    V/(T·V)
%      V_out/V_in = 65 · B̄_S   (B̄_S in Tesla → result in V/V)

clear; clc;

S = load('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\bs_matrix\data\B_bar.mat');
B      = S.B_matrix_at_Iin;       % Tesla (raw FEM, no sign correction)
I_in   = S.I_in_A;                 % 0.6 A

% S_hall = 0.130 V/mT  =  130 V/T  (user-confirmed unit 2026-05-19;
% the value stored in B_bar.mat as 0.13 V/T was a unit-label mistake)
S_hall_V_per_mT = 0.130;
S_hall          = S_hall_V_per_mT * 1000;   % V/T  ->  130

k_A    = 0.3;                       % A/V — per bs_derivation.pdf, Long Fei: 1 V → 0.3 A
coef   = k_A * S_hall / I_in;       % V/(T·V)  ->  65
fprintf('k_A    = %.4f A/V\n', k_A);
fprintf('I_in   = %.2f A\n', I_in);
fprintf('S_hall = %.3f V/mT  =  %.1f V/T\n', S_hall_V_per_mT, S_hall);
fprintf('coef   = k_A * S_hall / I_in = %.4f  V/(T*V)\n\n', coef);

V_out_V_in_matrix = coef * B;       % V/V (dimensionless)

%% Apply user sign convention (2026-05-19): diagonal = +|.|, off-diag = -|.|
for i = 1:6
    for j = 1:6
        if i == j
            V_out_V_in_matrix(i,j) = +abs(V_out_V_in_matrix(i,j));
        else
            V_out_V_in_matrix(i,j) = -abs(V_out_V_in_matrix(i,j));
        end
    end
end

%% Display
fprintf('V_out/V_in matrix  (V/V, k_A = %.2f, I_in = %.2f A) — off-diag forced negative:\n', k_A, I_in);
fprintf('     P1          P2          P3          P4          P5          P6\n');
for i = 1:6
    fprintf('P%d  ', i);
    for j = 1:6
        fprintf(' %+11.5f', V_out_V_in_matrix(i,j));
    end
    fprintf('\n');
end

fprintf('\nDiagonal (V/V):\n');
for i = 1:6
    layer = 'upper'; if ismember(i, [1 3 6]); layer = 'lower'; end
    fprintf('  P%d (%s)  = %+9.5f V/V\n', i, layer, V_out_V_in_matrix(i,i));
end

%% Save .mat
mat_out = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\bs_matrix\data\V_out_V_in_kA0p3.mat';
save(mat_out, 'V_out_V_in_matrix', 'B', 'I_in', 'S_hall', 'k_A', 'coef');
fprintf('\nSaved .mat: %s\n', mat_out);

%% LaTeX output — full derivation following bs_derivation.pdf
tex_file = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\Solve B_matrix\scripts\V_out_V_in_kA0p3_0p6A.tex';
fid = fopen(tex_file, 'w');
oc = onCleanup(@() fclose(fid));

fprintf(fid, '%% Auto-generated by magnetic_sim/ANSYS/main/matlab/long2016_hexapole_halfcut/fit/compute_V_out_V_in_kA0p3.m\n');
fprintf(fid, '\\documentclass[11pt,a4paper]{article}\n');
fprintf(fid, '\\usepackage[margin=1in]{geometry}\n');
fprintf(fid, '\\usepackage{booktabs}\n');
fprintf(fid, '\\usepackage{xcolor,colortbl}\n');
fprintf(fid, '\\begin{document}\n\n');

fprintf(fid, '\\begin{table}[htbp]\n\\centering\n\\small\n');
fprintf(fid, '\\begin{tabular}{c rrrrrr}\n\\toprule\n');
fprintf(fid, ' & P1 & P2 & P3 & P4 & P5 & P6 \\\\\n\\midrule\n');
for i = 1:6
    fprintf(fid, 'P%d', i);
    for j = 1:6
        v = V_out_V_in_matrix(i,j);   % V/V
        if i == j
            fprintf(fid, ' & \\cellcolor{yellow!20}$%+.5f$', v);
        else
            fprintf(fid, ' & $%+.5f$', v);
        end
    end
    fprintf(fid, ' \\\\\n');
end
fprintf(fid, '\\bottomrule\n\\end{tabular}\n');
fprintf(fid, '\\end{table}\n\n');

fprintf(fid, '\\end{document}\n');
fprintf('\nSaved LaTeX: %s\n', tex_file);
