%% compute_B_s_final.m — Final B_S matrix per user's convention
%
%  Steps:
%   (1) Start from B_matrix_at_Iin (FEM raw, Tesla)
%   (2) Flip upper coil columns (P2, P4, P5) — corrects ANSYS sign asymmetry
%   (3) Multiply by 130e-3 / I_in   → B_S in V/A
%   (4) Flip lower pole rows (P1, P3, P6) × -1   → user sign convention
%   (5) Output LaTeX

clear; clc;

S = load('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\bs_matrix\data\B_bar.mat');
B = S.B_matrix_at_Iin;          % Tesla
I_in   = S.I_in_A;              % 0.6 A
S_hall = S.S_hall;              % 0.13 V/T
coef   = S_hall / I_in;         % 0.2167 V/(T·A)

% Step 2: flip upper coil columns
upper_cols = [2 4 5];
B_corr = B;
B_corr(:, upper_cols) = -B_corr(:, upper_cols);

% Step 3: multiply by coefficient → B_S in V/A
B_S = coef * B_corr;

% Step 4: flip only the lower-lower off-diagonal entries (6 entries)
% so that ALL off-diag become negative while diag stay positive
lower = [1 3 6];
for ii = lower
    for jj = lower
        if ii ~= jj
            B_S(ii, jj) = -B_S(ii, jj);
        end
    end
end

%% Display
fprintf('B_S matrix [mV/A]:\n');
fprintf('     P1          P2          P3          P4          P5          P6\n');
for i = 1:6
    fprintf('P%d  ', i);
    for j = 1:6
        fprintf(' %+11.4f', B_S(i,j)*1e3);
    end
    fprintf('\n');
end

fprintf('\nDiagonal:\n');
for i = 1:6
    layer = 'upper'; if ismember(i, [1 3 6]); layer = 'lower'; end
    fprintf('  P%d (%s)  = %+8.4f mV/A\n', i, layer, B_S(i,i)*1e3);
end

%% Save
save('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\bs_matrix\data\B_s_final.mat', ...
     'B_S', 'B_corr', 'I_in', 'S_hall', 'upper_cols', 'lower');

%% Write LaTeX (follow style of B_s_matrix_0p6A.tex)
tex_file = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\Solve B_matrix\scripts\B_s_final_0p6A.tex';
fid = fopen(tex_file, 'w');
oc = onCleanup(@() fclose(fid));

fprintf(fid, '%% Auto-generated by magnetic_sim/ANSYS/main/matlab/long2016_hexapole_halfcut/fit/compute_B_s_final.m\n');
fprintf(fid, '\\documentclass[11pt,a4paper]{article}\n');
fprintf(fid, '\\usepackage[margin=1in]{geometry}\n');
fprintf(fid, '\\usepackage{booktabs}\n');
fprintf(fid, '\\usepackage{xcolor,colortbl}\n');
fprintf(fid, '\\usepackage{amsmath}\n\n');
fprintf(fid, '\\begin{document}\n\n');

fprintf(fid, '\\section*{$B_S$ matrix (mV/A) — final convention}\n\n');
fprintf(fid, 'Derivation per \\texttt{bs\\_derivation.pdf}:\n');
fprintf(fid, '\\[\n  B_S = \\dfrac{130 \\times 10^{-3}}{I_{in}}\\, \\overline{B}_S\n\\]\n');
fprintf(fid, 'For $I_{in} = %.2f$~A, $S_{hall} = 130$~mV/T:\n', I_in);
fprintf(fid, '\\[\n  B_S = %.4f \\times \\overline{B}_S \\quad [V/A]\n\\]\n\n', coef);
fprintf(fid, '\\noindent Sign convention: upper poles (P2, P4, P5) coil columns flipped to correct ANSYS winding asymmetry; lower-lower off-diagonal entries (6 entries among rows/cols P1, P3, P6) multiplied by $-1$ so that all diagonals are positive (self-response = emit) and all off-diagonals are negative (passive = receive).\n\n');

fprintf(fid, '\\begin{table}[htbp]\n\\centering\n\\small\n');
fprintf(fid, '\\begin{tabular}{c rrrrrr}\n\\toprule\n');
fprintf(fid, ' & P1 & P2 & P3 & P4 & P5 & P6 \\\\\n\\midrule\n');
for i = 1:6
    fprintf(fid, 'P%d', i);
    for j = 1:6
        v = B_S(i,j)*1e3;   % mV/A
        if i == j
            fprintf(fid, ' & \\cellcolor{yellow!20}$%+.4f$', v);
        else
            fprintf(fid, ' & $%+.4f$', v);
        end
    end
    fprintf(fid, ' \\\\\n');
end
fprintf(fid, '\\bottomrule\n\\end{tabular}\n');
fprintf(fid, '\\caption{$B_S$ matrix in mV/A. Rows = sensor index, columns = excited coil index. Diagonal highlighted.}\n');
fprintf(fid, '\\end{table}\n\n');

fprintf(fid, '\\end{document}\n');
fprintf('\nSaved LaTeX: %s\n', tex_file);

%% ---- Second LaTeX: B_S × k_A (V/V dimensionless) ----
k_A = 0.3614;
B_S_kA = B_S * k_A;     % V/V — Hall voltage per amplifier input voltage

fprintf('\nB_S × k_A (mV/V scale = ×10^-3 dimensionless):\n');
fprintf('     P1          P2          P3          P4          P5          P6\n');
for i = 1:6
    fprintf('P%d  ', i);
    for j = 1:6
        fprintf(' %+11.4f', B_S_kA(i,j)*1e3);
    end
    fprintf('\n');
end

tex_file2 = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\Solve B_matrix\scripts\B_s_kA_final_0p6A.tex';
fid2 = fopen(tex_file2, 'w');
oc2 = onCleanup(@() fclose(fid2));

fprintf(fid2, '%% Auto-generated by magnetic_sim/ANSYS/main/matlab/long2016_hexapole_halfcut/fit/compute_B_s_final.m\n');
fprintf(fid2, '\\documentclass[11pt,a4paper]{article}\n');
fprintf(fid2, '\\usepackage[margin=1in]{geometry}\n');
fprintf(fid2, '\\usepackage{booktabs}\n');
fprintf(fid2, '\\usepackage{xcolor,colortbl}\n');
fprintf(fid2, '\\usepackage{amsmath}\n\n');
fprintf(fid2, '\\begin{document}\n\n');

fprintf(fid2, '\\section*{$B_S \\cdot k_A$ matrix (dimensionless, $\\times 10^{-3}$ V/V)}\n\n');
fprintf(fid2, 'Per \\texttt{bs\\_derivation.pdf} considering amplifier gain $I_{in} = V_{in} \\cdot k_A$:\n');
fprintf(fid2, '\\[\n  B_S \\cdot k_A = \\dfrac{130 \\times 10^{-3} \\cdot k_A}{I_{in}}\\, \\overline{B}_S = \\dfrac{130 \\times 10^{-3}}{V_{in}}\\, \\overline{B}_S\n\\]\n');
fprintf(fid2, '\\noindent $I_{in} = %.2f$~A, $k_A = %.4f$~A/V, $V_{in} = I_{in}/k_A = %.4f$~V, $S_{hall} = 130$~mV/T.\n', I_in, k_A, I_in/k_A);
fprintf(fid2, '\\[\n  B_S \\cdot k_A = %.5f \\times \\overline{B}_S \\quad [V/V]\n\\]\n\n', coef*k_A);
fprintf(fid2, '\\noindent Same sign convention as $B_S$ table. All entries $\\times 10^{-3}$.\n\n');

fprintf(fid2, '\\begin{table}[htbp]\n\\centering\n\\small\n');
fprintf(fid2, '\\begin{tabular}{c rrrrrr}\n\\toprule\n');
fprintf(fid2, ' & P1 & P2 & P3 & P4 & P5 & P6 \\\\\n\\midrule\n');
for i = 1:6
    fprintf(fid2, 'P%d', i);
    for j = 1:6
        v = B_S_kA(i,j)*1e3;   % ×10^-3 V/V
        if i == j
            fprintf(fid2, ' & \\cellcolor{yellow!20}$%+.4f$', v);
        else
            fprintf(fid2, ' & $%+.4f$', v);
        end
    end
    fprintf(fid2, ' \\\\\n');
end
fprintf(fid2, '\\bottomrule\n\\end{tabular}\n');
fprintf(fid2, '\\caption{$B_S \\cdot k_A$ matrix ($\\times 10^{-3}$ V/V). Rows = sensor index, columns = excited coil index (via amplifier input).}\n');
fprintf(fid2, '\\end{table}\n\n');
fprintf(fid2, '\\end{document}\n');

% Save mat too
save('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\bs_matrix\data\B_s_kA_final.mat', ...
     'B_S_kA', 'B_S', 'B_corr', 'I_in', 'S_hall', 'k_A', 'upper_cols', 'lower');

fprintf('\nSaved LaTeX (×k_A): %s\n', tex_file2);
