%% gen_Vout_Vin_latex.m — LaTeX (math bmatrix) for V_out/V_in = k_A * B_S
%
%  V_out/V_in (per bs_derivation.pdf) = k_A * B_S, dimensionless (V/V).
%    B_S  = Bs.mat  (V/A; = (S_hall/I_in)*B_bar_S; diag +, off-diag - convention)
%    k_A  = 0.36 A/V   (amplifier gain)
%    V_out/V_in = k_A * B_S
%
%  Sign convention inherited from B_S: diagonal +|.|, off-diagonal -|.|
%  (k_A is a positive scalar, so the pattern is unchanged).

clear; clc;

S = load('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\bs_matrix\data\Bs.mat');
B_S = S.B_S;                       % V/A

k_A = 0.36;                        % A/V
V_VV = k_A * B_S;                  % V/V (dimensionless)

fprintf('k_A = %.2f A/V\n', k_A);
fprintf('\nV_out/V_in [V/V]  (diag +, off-diag - convention):\n');
fprintf('      P1         P2         P3         P4         P5         P6\n');
for i = 1:6
    fprintf('P%d ', i);
    for j = 1:6
        fprintf(' %+10.4f', V_VV(i,j));
    end
    fprintf('\n');
end
fprintf('\ndiagonal (V/V): %s\n', mat2str(diag(V_VV).',5));

%% --- save .mat ---
mat_out = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\bs_matrix\data\Vout_Vin_kA0p36.mat';
save(mat_out, 'V_VV', 'k_A', 'B_S');
fprintf('\nSaved .mat: %s\n', mat_out);

%% --- LaTeX: V_out/V_in = bmatrix ... ---
tex_file = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\Solve B_matrix\scripts\Vout_Vin_kA0p36.tex';
fid = fopen(tex_file, 'w');
oc  = onCleanup(@() fclose(fid));

fprintf(fid, '%% Auto-generated by magnetic_sim/ANSYS/main/matlab/long2016_hexapole_halfcut/fit/gen_Vout_Vin_latex.m\n');
fprintf(fid, '\\documentclass[11pt]{article}\n');
fprintf(fid, '\\usepackage[margin=1in]{geometry}\n');
fprintf(fid, '\\usepackage{amsmath}\n');
fprintf(fid, '\\begin{document}\n\n');
fprintf(fid, '\\[\n\\frac{V_{out}}{V_{in}} = \\begin{bmatrix}\n');
for i = 1:6
    for j = 1:6
        fprintf(fid, '%+9.4f', V_VV(i,j));
        if j < 6, fprintf(fid, ' & '); end
    end
    fprintf(fid, ' \\\\\n');
end
fprintf(fid, '\\end{bmatrix}\n\\]\n\n');
fprintf(fid, ['\\noindent $V_{out}/V_{in} = k_A\\,B_S$ (dimensionless),\\ ' ...
              'with $k_A = %.2f$\\,A/V.\\\\\n'], k_A);
fprintf(fid, ['Row $i$ = $B_{\\mathrm{surface}}$ sensor on pole $i$;\\ ' ...
              'column $j$ = excited pole $j$;\\ order P1--P6.\\\\\n']);
fprintf(fid, ['Sign convention: diagonal $+|\\cdot|$, off-diagonal $-|\\cdot|$.\n']);
fprintf(fid, '\n\\end{document}\n');

fprintf('Saved LaTeX: %s\n', tex_file);
