%% gen_Bbar_S_latex.m — LaTeX (math bmatrix) for the B_bar_S matrix
%
%  B_bar_S (per bs_derivation.pdf) = 6x6 magnetic-flux-density matrix:
%    entry (i,j) = B measured by the B_surface Hall sensor on pole i when
%    pole j is the excited pole, in Tesla at test current I_in.
%
%  Data: magnetic_sim/ANSYS/main/MATLAB_data/long2016_hexapole_halfcut/bs_matrix/B_bar.mat
%    -> variable B_matrix_at_Iin  IS  B_bar_S (raw FEM, halfcut, 37-pt disc).
%    (the variable named 'B_bar' in that .mat is an OLD V_out/V_in result
%     = 0.0783 * B_matrix_at_Iin, 0.0783 = k_A*S_hall/I_in; NOT B_bar_S.)
%
%  Sign convention (user): diagonal +|.|, off-diagonal -|.|.
%  Row/col order: paper poles P1..P6 (notation-glossary.md).

clear; clc;

S = load('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\bs_matrix\B_bar.mat');

% --- report what's in the .mat ---
fprintf('B_bar.mat variables: %s\n', strjoin(fieldnames(S),', '));
Bbar_S = S.B_matrix_at_Iin;        % Tesla @ I_in  -- this is B_bar_S
I_in   = S.I_in_A;
fprintf('Using B_matrix_at_Iin as B_bar_S.  I_in = %.2f A\n', I_in);
fprintf('raw diagonal (T): %s\n\n', mat2str(diag(Bbar_S).',4));

%% --- apply sign convention: diag +|.|, off-diag -|.| ---
for i = 1:6
    for j = 1:6
        if i == j
            Bbar_S(i,j) = +abs(Bbar_S(i,j));
        else
            Bbar_S(i,j) = -abs(Bbar_S(i,j));
        end
    end
end

%% --- display ---
fprintf('B_bar_S (T, sign: diag +, off-diag -):\n');
fprintf('      P1          P2          P3          P4          P5          P6\n');
for i = 1:6
    fprintf('P%d ', i);
    for j = 1:6
        fprintf(' %+11.4e', Bbar_S(i,j));
    end
    fprintf('\n');
end

%% --- save .mat ---
mat_out = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\bs_matrix\Bbar_S.mat';
save(mat_out, 'Bbar_S', 'I_in');
fprintf('\nSaved .mat: %s\n', mat_out);

%% --- LaTeX: B_bar_S = 1e-3 * bmatrix ... T ---
tex_file = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\Solve B_matrix\scripts\Bbar_S_matrix.tex';
fid = fopen(tex_file, 'w');
oc  = onCleanup(@() fclose(fid));

M = Bbar_S * 1e3;     % factor 10^-3 out; entries become O(0.1..20)

fprintf(fid, '%% Auto-generated by magnetic_sim/ANSYS/main/matlab/long2016_hexapole_halfcut/fit/gen_Bbar_S_latex.m\n');
fprintf(fid, '\\documentclass[11pt]{article}\n');
fprintf(fid, '\\usepackage[margin=1in]{geometry}\n');
fprintf(fid, '\\usepackage{amsmath}\n');
fprintf(fid, '\\begin{document}\n\n');
fprintf(fid, '\\[\n\\bar{B}_S = 10^{-3}\n\\begin{bmatrix}\n');
for i = 1:6
    for j = 1:6
        fprintf(fid, '%+8.3f', M(i,j));
        if j < 6, fprintf(fid, ' & '); end
    end
    fprintf(fid, ' \\\\\n');
end
fprintf(fid, '\\end{bmatrix}\\ \\mathrm{T}\n\\]\n\n');
fprintf(fid, ['\\noindent Row $i$ = $B_{\\mathrm{surface}}$ sensor on pole $i$;\\ ' ...
              'column $j$ = excited pole $j$;\\ order P1--P6;\\ ' ...
              'test current $I_{in} = %.2f$\\,A.\n'], I_in);
fprintf(fid, '\n\\end{document}\n');

fprintf('Saved LaTeX: %s\n', tex_file);
