%% gen_Bs_latex.m — LaTeX (math bmatrix) for the B_S matrix [V/A]
%
%  B_S (per bs_derivation.pdf) = V_ij / I_in = (S_hall / I_in) * B_bar_S,
%  units V/A — the Hall-voltage-per-input-current transfer matrix.
%
%    B_bar_S  = B_bar.mat -> B_matrix_at_Iin  (raw FEM, halfcut, 37-pt disc,
%               Tesla @ I_in)
%    S_hall   = 130 V/T   (= 0.130 V/mT; bs_derivation writes 130e-3)
%    I_in     = 0.6 A
%    B_S      = (S_hall / I_in) * B_bar_S
%
%  Sign: OUTPUT presentation convention — diagonal +|.|, off-diagonal -|.|
%  (user-requested "off-diagonal negative" version). NOTE: this is a display
%  convention only; the raw-data principle (keep physical signed B.n+) still
%  holds for the underlying extraction — see memory sensor-sign-convention.

clear; clc;

S = load('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\bs_matrix\data\B_bar.mat');
Bbar_S = S.B_matrix_at_Iin;        % Tesla @ I_in  (raw)
I_in   = S.I_in_A;                 % 0.6 A

S_hall = 130;                      % V/T  (= 0.130 V/mT)
coef   = S_hall / I_in;            % V/(A*T)
B_S    = coef * Bbar_S;            % V/A

% output presentation convention: diagonal +|.|, off-diagonal -|.|
for i = 1:6
    for j = 1:6
        if i == j
            B_S(i,j) = +abs(B_S(i,j));
        else
            B_S(i,j) = -abs(B_S(i,j));
        end
    end
end

fprintf('S_hall = %g V/T,  I_in = %.2f A,  coef = S_hall/I_in = %.4f V/(A*T)\n', ...
        S_hall, I_in, coef);
fprintf('\nB_S [V/A]  (diag +, off-diag - convention):\n');
fprintf('      P1         P2         P3         P4         P5         P6\n');
for i = 1:6
    fprintf('P%d ', i);
    for j = 1:6
        fprintf(' %+10.4f', B_S(i,j));
    end
    fprintf('\n');
end
fprintf('\ndiagonal (V/A): %s\n', mat2str(diag(B_S).',5));

%% --- save .mat ---
mat_out = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\bs_matrix\data\Bs.mat';
save(mat_out, 'B_S', 'S_hall', 'I_in', 'coef');
fprintf('\nSaved .mat: %s\n', mat_out);

%% --- LaTeX: B_S = bmatrix ... V/A ---
tex_file = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\Solve B_matrix\scripts\Bs_matrix.tex';
fid = fopen(tex_file, 'w');
oc  = onCleanup(@() fclose(fid));

fprintf(fid, '%% Auto-generated by magnetic_sim/ANSYS/main/matlab/long2016_hexapole_halfcut/fit/gen_Bs_latex.m\n');
fprintf(fid, '\\documentclass[11pt]{article}\n');
fprintf(fid, '\\usepackage[margin=1in]{geometry}\n');
fprintf(fid, '\\usepackage{amsmath}\n');
fprintf(fid, '\\begin{document}\n\n');
fprintf(fid, '\\[\nB_S = \\begin{bmatrix}\n');
for i = 1:6
    for j = 1:6
        fprintf(fid, '%+9.4f', B_S(i,j));
        if j < 6, fprintf(fid, ' & '); end
    end
    fprintf(fid, ' \\\\\n');
end
fprintf(fid, '\\end{bmatrix}\\ \\mathrm{V/A}\n\\]\n\n');
fprintf(fid, ['\\noindent $B_S = (S_{hall}/I_{in})\\,\\bar{B}_S$,\\ ' ...
              'with $S_{hall} = 130$\\,V/T and $I_{in} = %.2f$\\,A.\\\\\n'], I_in);
fprintf(fid, ['Row $i$ = $B_{\\mathrm{surface}}$ sensor on pole $i$;\\ ' ...
              'column $j$ = excited pole $j$;\\ order P1--P6.\\\\\n']);
fprintf(fid, ['Sign convention: diagonal $+|\\cdot|$, off-diagonal ' ...
              '$-|\\cdot|$ (magnitudes are $|(S_{hall}/I_{in})\\,\\bar{B}_S|$).\n']);
fprintf(fid, '\n\\end{document}\n');

fprintf('Saved LaTeX: %s\n', tex_file);
