%% gen_Bbar_S_4p572.m
%  ------------------------------------------------------------------
%  Generate B_bar_S matrix LaTeX for Long Fei halfcut baseline FEM at
%  sensor 4.572 mm. Per magnetic_sim/ANSYS/main/doc/Solve_B_matrix/.../Bs_derivation.pdf:
%
%      V_ij = S_hall * B_ij                      (eq 1, S_hall = 130 V/T = 0.13 V/mT)
%      V_ij / I_in = (130 * 10^-3 / I_in) * B_bar_S = B_S    (eq 2)
%      V_out/V_in = k_A * B_S                    (eq 3)
%
%  → B_bar_S is the raw FEM 6x6 B matrix entries in mT at the test I_in.
%    (the factor 10^-3 in PDF eq 2 converts mT -> T so that 130 V/T * 10^-3 = 0.13 V/mT.)
%
%  Reads from new Vout_Vin_4p572.mat (S_hall=130 V/T unit-fixed, 2026-05-26)
%  which has B_matrix_at_Iin_T (Tesla); we convert to mT for display.
%
%  Outputs:
%    magnetic_sim/ANSYS/main/MATLAB_data/long2016_hexapole_halfcut/bs_matrix/Bbar_S_4p572.mat
%    magnetic_sim/ANSYS/main/doc/Solve_B_matrix/long2016_hexapole_halfcut/scripts/Bbar_S_4p572.tex
%  ------------------------------------------------------------------

clear; clc;

%% --- Load baseline FEM data ---
src_mat = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\bs_matrix\Vout_Vin_4p572.mat';
if ~exist(src_mat, 'file')
    error('Source mat not found: %s\nRun gen_Vout_Vin_4p572.m first.', src_mat);
end
S = load(src_mat, 'B_matrix_at_Iin_T', 'I_in_A', 'sensor_along_mm', 'sensor_offset_mm');

Bbar_S_T_raw  = S.B_matrix_at_Iin_T;        % T at I_in_A (raw FEM, after S_hall unit fix)
I_in_A        = S.I_in_A;

fprintf('Loaded: %s\n', src_mat);
fprintf('Sensor placement: %.3f mm axial + %.2f mm normal\n', ...
        S.sensor_along_mm, S.sensor_offset_mm);
fprintf('I_in = %.2f A\n\n', I_in_A);

%% --- Per-pole sign correction (diag → all positive) ---
%  For each pole j, if Bbar_S(j,j) < 0 in raw FEM, multiply column j by -1.
%  This redefines "+I" direction per pole so that diagonal = "B aligned with
%  sensor n+" is always positive. Physical interpretation: "+I_j produces
%  flux flowing yoke → tip_j → WP".
col_sign  = sign(diag(Bbar_S_T_raw))';      % 1x6 row, +1 or -1 per column
Bbar_S_T  = Bbar_S_T_raw .* col_sign;       % column-wise multiply
Bbar_S_mT = Bbar_S_T * 1000;

fprintf('Raw FEM diag signs (pre-correction): %s\n', mat2str(col_sign));
fprintf('Sign flip applied to columns: %s\n\n', mat2str(find(col_sign < 0)));

fprintf('B_bar_S raw (T, pre sign correction):\n');
fprintf('      P1          P2          P3          P4          P5          P6\n');
for i = 1:6
    fprintf('P%d ', i);
    for j = 1:6
        fprintf(' %+9.4f', Bbar_S_T_raw(i,j) * 1000);   % display in mT
    end
    fprintf('\n');
end
fprintf('\nB_bar_S sign-corrected (mT, all diag positive):\n');
fprintf('      P1          P2          P3          P4          P5          P6\n');
for i = 1:6
    fprintf('P%d ', i);
    for j = 1:6
        fprintf(' %+9.4f', Bbar_S_mT(i,j));
    end
    fprintf('\n');
end

%% --- Display = sign-corrected (all diagonals positive) ---
Bbar_S_mT_disp = Bbar_S_mT;     % already sign-corrected above

%% --- Save .mat ---
data_dir = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\bs_matrix';
if ~exist(data_dir, 'dir'); mkdir(data_dir); end
mat_out = fullfile(data_dir, 'Bbar_S_4p572.mat');
sensor_along_mm  = S.sensor_along_mm;
sensor_offset_mm = S.sensor_offset_mm;
save(mat_out, 'Bbar_S_T', 'Bbar_S_mT', 'Bbar_S_mT_disp', 'Bbar_S_T_raw', ...
              'col_sign', 'I_in_A', 'sensor_along_mm', 'sensor_offset_mm');
fprintf('\nSaved .mat: %s\n', mat_out);

%% --- LaTeX: B_bar_S in T directly (no 10^-3 factor out) ---
Bbar_S_T_disp = Bbar_S_mT_disp / 1000;   % cosmetic-signed, in T

tex_dir  = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\Solve_B_matrix\long2016_hexapole_halfcut\scripts';
if ~exist(tex_dir, 'dir'); mkdir(tex_dir); end
tex_file = fullfile(tex_dir, 'Bbar_S_4p572.tex');

fid = fopen(tex_file, 'w');
oc  = onCleanup(@() fclose(fid));

fprintf(fid, '%% Auto-generated by magnetic_sim/ANSYS/main/matlab/long2016_hexapole_halfcut/fit/gen_Bbar_S_4p572.m\n');
fprintf(fid, '%% Source: Long Fei halfcut FEM baseline (coil1_pre_fine_mesh + coil2..6)\n');
fprintf(fid, '%% Sensor: 4.572 mm along pole surface + 0.41 mm normal, Ø0.3 mm disc, 721-pt sampling\n');
fprintf(fid, '%% B_bar_S entries in TESLA (direct, no 10^-3 factor)\n');
fprintf(fid, '\\documentclass[11pt]{article}\n');
fprintf(fid, '\\usepackage[margin=1in]{geometry}\n');
fprintf(fid, '\\usepackage{amsmath}\n');
fprintf(fid, '\\begin{document}\n\n');
fprintf(fid, '\\[\n\\bar{B}_S =\n\\begin{bmatrix}\n');
for i = 1:6
    for j = 1:6
        fprintf(fid, '%+10.6f', Bbar_S_T_disp(i,j));
        if j < 6, fprintf(fid, ' & '); end
    end
    fprintf(fid, ' \\\\\n');
end
fprintf(fid, '\\end{bmatrix}\\ \\mathrm{T}\n\\]\n\n');
fprintf(fid, ['\\noindent Geometry: Long Fei halfcut hexapole (lower poles milled), $\\mu_r = 280$, ' ...
              'baseline FEM (no air gap).\\\\\n']);
fprintf(fid, ['Sensor: %.3f mm along pole surface from tip + %.2f mm perpendicular ' ...
              '(0.3 mm $\\varnothing$ Hall disc, 721-pt sampling).\\\\\n'], ...
              sensor_along_mm, sensor_offset_mm);
fprintf(fid, ['Test current $I_{in} = %.2f$~A (each coil excited individually with 70 turns).\\\\\n'], I_in_A);
fprintf(fid, ['Row $i$ = $B_{\\mathrm{surface}}$ sensor on pole $i$;\\ ' ...
              'column $j$ = excited pole $j$;\\ order P1--P6.\\\\\n']);
fprintf(fid, ['Sign convention: per-pole sign correction applied — for each pole $j$, ' ...
              'column $j$ of raw FEM matrix is multiplied by $\\mathrm{sign}(\\bar{B}_S(j,j))$ ' ...
              'so that all diagonals are positive. ' ...
              'Physical interpretation: "$+I_j$" is redefined per pole such that ' ...
              '"$+I$ produces flux flowing yoke $\\to$ tip $\\to$ WP".\\\\\n']);
fprintf(fid, 'Columns sign-flipped vs raw FEM: %s.\\\\\n', mat2str(find(col_sign < 0)));
fprintf(fid, ['Sensor normal $\\hat{n}_+$ in pole-local: lower (P1/P3/P6) = $(0,1,0)$ flat surface; ' ...
              'upper (P2/P4/P5) = $(-\\sin\\beta,\\cos\\beta,0)$ tilted slant, $\\beta = ' ...
              '\\arctan(3/15) \\approx 11.31^\\circ$.\n']);
fprintf(fid, '\n\\end{document}\n');

fprintf('Saved LaTeX: %s\n', tex_file);
