%% verify_G_vs_Dv.m -- 驗證 fix_dir 的 G = gB·K̄·F 是否等於 Hall_sensor_base_fix_dir 的 D^v
% =========================================================================
% G = gB·Khat·F（fix-l 電荷模型轉成 coil 激發序的每激發電荷）；
% D^v = Hall_sensor_base_fix_dir/main_Dmatrix 的 profiled 每激發電荷((AᵀA)⁻¹AᵀBstack)。
% 兩者同 ℓ、同 on-axis kernel、且 fix_dir 已轉 flip-sink → 應【直接】相等（無需 coil_sign）。
% 輸出 xelatex PDF → fix_dir/results/G_vs_Dv_<variant>.pdf（results 只留 .pdf）。
% =========================================================================
clear; clc;
VARIANT = 'gap200um_mueq';
CAL = ['G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\' ...
       'long2016_hexapole_halfcut\Calibration_using_FEM_modeling'];
out_dir = fullfile(CAL,'fix_dir','results');

apdl_to_paper_idx = [1,3,6,5,2,4];
F = zeros(6,6); for j=1:6, F(apdl_to_paper_idx(j),j)=1; end   % 電流置換：列=paper、欄=coil

% ---- fix_dir：G = gB·Khat·F（欄=coil APDL 激發；Khat 已 flip-sink）----
S = load(fullfile(CAL,'fix_dir','data',sprintf('fit_fixl_R150um_%s.mat',VARIANT)));   % ell,gB,Khat
G = S.gB * S.Khat * F;

% ---- Hall：D^v（Dv_p paper 欄 → 轉回 APDL 欄）----
H = load(fullfile(CAL,'Hall_sensor_base_fix_dir','data',sprintf('calib_D_%s.mat',VARIANT)));  % Dv_p,ell_hat
Dv = H.Dv_p(:, apdl_to_paper_idx);

% ---- 欄重排回 paper P1..P6 顯示（對角=自激發）----
[~, paper_to_apdl] = sort(apdl_to_paper_idx);
Gp  = G(:,  paper_to_apdl);
Dvp = Dv(:, paper_to_apdl);
dmax = max(abs(G(:)-Dv(:)));  relref = max(abs(Dv(:)));

fprintf('ℓ：fix_dir=%.4f mm / Hall=%.4f mm（Δ=%.2e）；gB=%.4e\n', S.ell*1e3, H.ell_hat*1e3, (S.ell-H.ell_hat)*1e3, S.gB);
fprintf('max|G − D^v| = %.3e（相對 %.2e）→ %s\n', dmax, dmax/relref, ternary(dmax/relref<1e-6,'完全相等','不相等'));
fprintf('G (paper 欄)：\n');  for i=1:6, fprintf('  % .4e % .4e % .4e % .4e % .4e % .4e\n', Gp(i,:)); end

%% ---- xelatex PDF ----------------------------------------------------------
pole = {'P1','P2','P3','P4','P5','P6'};
tex_path = fullfile(out_dir, sprintf('G_vs_Dv_%s.tex', VARIANT));
pdf_path = fullfile(out_dir, sprintf('G_vs_Dv_%s.pdf', VARIANT));
fid = fopen(tex_path,'w');
fprintf(fid,'%% Auto-generated by verify_G_vs_Dv.m\n');
fprintf(fid,'\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\begin{document}\n');
fprintf(fid,'\\begin{center}\\large Verify $G=g_B\\hat{K}F$ \\;vs\\; Hall $D^{v}$\\quad(variant: %s)\\end{center}\n\n', strrep(VARIANT,'_','\_'));
emit_mat(fid,'G = g_B\hat{K}F', Gp, pole, 'auto', ...
    'row $i$ = charge pole P$i$;\ column $j$ = excited pole P$j$ (diagonal = self);\ from fix-dir charge fit (flip-sink);\ units T.');
emit_mat(fid,'D^{v}', Dvp, pole, 'auto', ...
    'row $i$ = charge pole P$i$;\ column $j$ = excited pole P$j$;\ Hall-sensor-base-fix-dir profiled charges;\ units T.');
fprintf(fid,['\\noindent\\small $\\hat{\\ell}_{\\mathrm{fix}}=%.4f$\\,mm,\\ $\\hat{\\ell}_{\\mathrm{Hall}}=%.4f$\\,mm;\\ $g_B=%.4e$;\\ ' ...
             'both flip-sink (only-sink lower P1/P3/P6);\\ $\\max|G-D^{v}|=%.2e$ (rel.\\ %.2e)\\ $\\Rightarrow$ \\textbf{%s}.\n'], ...
        S.ell*1e3, H.ell_hat*1e3, S.gB, dmax, dmax/relref, ternary(dmax/relref<1e-6,'identical','NOT equal'));
fprintf(fid,'\\end{document}\n'); fclose(fid);

xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
old=cd(out_dir); [st,so]=system(sprintf('"%s" -interaction=nonstopmode -halt-on-error "%s"',xelatex,tex_path)); cd(old);
if st~=0 || ~exist(pdf_path,'file'); fprintf('%s\n',so); error('xelatex 編譯失敗'); end
for e={'.tex','.aux','.log','.out'}, f=fullfile(out_dir,sprintf('G_vs_Dv_%s%s',VARIANT,e{1})); if exist(f,'file'); delete(f); end, end
fprintf('已存 %s\n', pdf_path);

%% ---- locals ----
function emit_mat(fid, name, M, lab, fmode, cap)
    Ms=M; fac='';
    if strcmp(fmode,'auto'), mx=max(abs(M(:))); if mx>0, e=floor(log10(mx)); if e~=0, Ms=M/10^e; fac=sprintf('10^{%d}\\,',e); end, end, end
    fprintf(fid,'\\[\n%s = %s\\begin{array}{c|cccccc}\n ',name,fac);
    for j=1:6, fprintf(fid,'& %s ',lab{j}); end
    fprintf(fid,'\\\\\\hline\n');
    for i=1:6, fprintf(fid,'%s ',lab{i}); for j=1:6, fprintf(fid,'& %+9.4f ',Ms(i,j)); end, fprintf(fid,'\\\\\n'); end
    fprintf(fid,'\\end{array}\n\\]\n\\noindent\\small %s\n\n',cap);
end
function out = ternary(c,a,b), if c, out=a; else, out=b; end, end
