function compute_vmatrix()
% COMPUTE_VMATRIX  依 vmatrix.pdf 公式算 V 矩陣並輸出獨立 PDF 到本組 results/。
%   公式：V(i,j) = I · (1/k_j) · B(i,j)   即 V = I · B · diag(1./k)（每欄 j 除以 k_j 再乘 I）。
%   I = 0.6 × 1.67（操作電流 0.6 A × 增益補正 1.67）；B、k 取自 vmatrix.pdf。
%   輸出：results/vmatrix.pdf（另外輸出，不動既有 D_gap200um_mueq.pdf）。

    %% ---- 輸入（來自 vmatrix.pdf）--------------------------------------------
    I = 0.6 * 1.67;                                       % = 1.002 A
    B = [ 0.2816 -0.0052 -0.0406 -0.0305 -0.0316 -0.0505;
         -0.0111  0.2659 -0.0423 -0.0666 -0.0756 -0.0346;
         -0.0470 -0.0332  0.2995 -0.0064 -0.0237 -0.0550;
         -0.0308 -0.0646 -0.0129  0.2348 -0.0833 -0.0193;
         -0.0411 -0.0661 -0.0217 -0.0760  0.2537 -0.0118;
         -0.0477 -0.0208 -0.0402 -0.0250 -0.0056  0.2302 ];
    k = [0.3618, 0.3614, 0.3536, 0.3532, 0.3573, 0.3610]; % 1×6，每欄 j 的 k_j

    %% ---- 計算 V = I · B · diag(1./k)（每欄 j 除以 k_j，再乘 I）--------------
    V = I * (B ./ k);                                    % k 為 1×6 → 廣播：欄 j 同除 k_j

    %% ---- console 印 --------------------------------------------------------
    fprintf('I = 0.6*1.67 = %.4f\n', I);
    fprintf('V = I·B·diag(1./k)：\n');
    for i = 1:6, fprintf('  % .5f % .5f % .5f % .5f % .5f % .5f\n', V(i,:)); end

    %% ---- 輸出獨立 PDF 到本組 results/ --------------------------------------
    here    = fileparts(mfilename('fullpath'));            % .../code/function
    out_dir = fullfile(fileparts(here), '..', 'results');  % .../Hall_sensor_base_fix_dir/results
    out_dir = char(java.io.File(out_dir).getCanonicalPath());
    if ~exist(out_dir,'dir'); mkdir(out_dir); end
    pole = {'P1','P2','P3','P4','P5','P6'};
    tex_path = fullfile(out_dir,'vmatrix.tex');
    pdf_path = fullfile(out_dir,'vmatrix.pdf');
    fid = fopen(tex_path,'w');
    fprintf(fid,'%% Auto-generated by compute_vmatrix.m — V = I*B*diag(1/k)\n');
    fprintf(fid,'\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\usepackage{amssymb}\n');
    fprintf(fid,'\\begin{document}\n');
    fprintf(fid,'\\begin{center}\\large $V = I\\cdot B\\cdot\\mathrm{diag}(1/k)$\\quad($I=0.6\\times1.67=%.4f$)\\end{center}\n\n', I);
    emit_labeled_matrix(fid, 'V', V, pole, pole, 'auto', ...
        sprintf(['$V_{ij}=I\\,B_{ij}/k_j$;\\ row $i$, column $j$;\\ $I=0.6\\times1.67=%.4f$;\\ ' ...
                 '$k=[%.4f\\ %.4f\\ %.4f\\ %.4f\\ %.4f\\ %.4f]$;\\ $B$, $k$ from vmatrix.pdf.'], I, k));
    fprintf(fid,'\\end{document}\n');
    fclose(fid);

    xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
    old = cd(out_dir);
    [st,sysout] = system(sprintf('"%s" -interaction=nonstopmode -halt-on-error "%s"', xelatex, tex_path));
    cd(old);
    if st ~= 0 || ~exist(pdf_path,'file'); fprintf('%s\n', sysout); error('xelatex 編譯失敗'); end
    for ext = {'.tex','.aux','.log','.out'}    % results 只留 .pdf
        f = fullfile(out_dir,['vmatrix' ext{1}]); if exist(f,'file'); delete(f); end
    end
    fprintf('已存 %s\n', pdf_path);
end

%% ---- local：渲染帶 P1..P6 表頭的 6×6 矩陣（含自動 10^n 因子）--------------
function emit_labeled_matrix(fid, name_tex, M, rowlab, collab, factor_mode, caption)
    if strcmp(factor_mode,'auto')
        mx = max(abs(M(:)));
        if mx > 0, e = floor(log10(mx)); else, e = 0; end
        if e ~= 0, Ms = M / 10^e; fac = sprintf('10^{%d}\\,', e); else, Ms = M; fac = ''; end
    else
        Ms = M; fac = '';
    end
    fprintf(fid,'\\[\n%s = %s\\begin{array}{c|cccccc}\n', name_tex, fac);
    fprintf(fid,' ');
    for j = 1:6, fprintf(fid,'& %s ', collab{j}); end
    fprintf(fid,'\\\\\\hline\n');
    for i = 1:6
        fprintf(fid,'%s ', rowlab{i});
        for j = 1:6, fprintf(fid,'& %+9.4f ', Ms(i,j)); end
        fprintf(fid,'\\\\\n');
    end
    fprintf(fid,'\\end{array}\n\\]\n');
    fprintf(fid,'\\noindent\\small %s\n\n', caption);
end
