function write_d_tex(tex_path, mode, d, Vp, gH, S)
% WRITE_D_TEX  出 per-pole d 的 standalone LaTeX(mode='v2' 無增益 / 'final' 含 g_H)。
%   Vp = 欄重排成「激發 paper pole P1..P6」的 sensor 電壓;S = 含 ell_hat/R_select/
%   S_hall/nrmse_sensor 的設定 struct。 (ported verbatim from gen_d_latex.m local function)
    fid = fopen(tex_path,'w');
    fprintf(fid,'%% Auto-generated by sensor_d/main.m (write_d_tex) -- Hall-sensor-based per-pole d (%s)\n', mode);
    fprintf(fid,'\\documentclass[11pt,a4paper]{article}\n');
    fprintf(fid,'\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\usepackage{booktabs}\n\\usepackage{xcolor,colortbl}\n');
    fprintf(fid,'\\begin{document}\n\n');
    fprintf(fid,'\\section*{Hall-sensor-based hexapole model --- per-pole calibration $\\mathbf{d}$}\n\n');

    % --- model 描述(兩版不同)---
    if strcmp(mode,'v2')
        fprintf(fid,'Model (\\emph{Calibration using FEM modeling\\_V2.pdf}, page 2 --- no explicit gain): $\\boldsymbol{\\varepsilon}_{ij}=\\mathbf{b}_{ij}-\\mathbf{S}_i\\mathbf{V}_j\\mathbf{d}$, i.e. $\\mathbf{b}_{ij}=\\sum_k d_k v_{jk}\\mathbf{s}_{ik}$. ');
        fprintf(fid,'Closed form $\\mathbf{d}=\\big(\\sum_{i,j}\\mathbf{V}_j\\mathbf{S}_i^{\\top}\\mathbf{S}_i\\mathbf{V}_j\\big)^{-1}\\big(\\sum_{i,j}\\mathbf{V}_j\\mathbf{S}_i^{\\top}\\mathbf{b}_{ij}\\big)$. The gain is absorbed into $\\mathbf{d}$; it relates to the gain version by $\\mathbf{d}=g_H\\,\\mathbf{d}_{\\mathrm{final}}$ with $g_H=%.4e~\\mathrm{m^{-2}}$.\n\n', gH);
    else
        fprintf(fid,'Model (\\emph{hw.pdf} --- explicit gain $g_H$): $\\boldsymbol{\\varepsilon}_{ij}=\\mathbf{b}_{ij}-g_H\\,\\mathbf{S}_i\\mathbf{V}_j\\mathbf{d}$, with $g_H=\\dfrac{k_m}{\\widehat{\\ell}^{2}\\mu_0}=\\dfrac{1}{4\\pi\\widehat{\\ell}^{2}}=%.4e~\\mathrm{m^{-2}}$ ', gH);
        fprintf(fid,'(from $\\widehat{\\mathbf{Q}}_j=\\widehat{\\boldsymbol{\\Phi}}_j/\\mu_0$, $\\mathbf{b}=\\tfrac{k_m}{\\widehat{\\ell}^2}\\mathbf{S}\\widehat{\\mathbf{Q}}$). ');
        fprintf(fid,'Closed form $\\mathbf{d}=\\dfrac{1}{g_H}\\big(\\sum_{i,j}\\mathbf{V}_j\\mathbf{S}_i^{\\top}\\mathbf{S}_i\\mathbf{V}_j\\big)^{-1}\\big(\\sum_{i,j}\\mathbf{V}_j\\mathbf{S}_i^{\\top}\\mathbf{b}_{ij}\\big)=4\\pi\\widehat{\\ell}^{2}\\big(\\cdots\\big)=\\mathbf{d}_{\\mathrm{V2}}/g_H$.\n\n');
    end

    % --- 設定 ---
    fprintf(fid,'\\noindent\\textbf{Settings.} $\\widehat{\\ell}=%.3f$~mm (from the $R\\le150\\,\\mu$m all-node fit), fit region $R\\le%d\\,\\mu$m, $S_{\\mathrm{hall}}=%g$~V/T, sensor at $4.572$~mm from apex $+\\,0.41$~mm off the surface. ', S.ell_hat*1e3, round(S.R_select*1e6), S.S_hall);
    fprintf(fid,'Sign convention: signed component $S_{\\mathrm{hall}}(\\mathbf{B}\\!\\cdot\\!\\mathbf{n}_+)$ along $\\mathbf{n}_+$ (outward from steel; lower $\\perp$ milled flat, upper $\\perp$ cone face), \\emph{all-source} (lower-pole excitations P1/P3/P6 sign-flipped, $\\equiv$ reversing those windings since $\\mathbf{B}$ is linear in current), so the diagonal (self-actuation) is positive.\n\n');

    % --- d 向量(動態共同指數)---
    pe = floor(log10(max(abs(d))));
    fprintf(fid,'\\[\n\\mathbf{d}=\\begin{bmatrix}\n');
    for i=1:6, fprintf(fid,'d_{\\mathrm{P%d}} \\\\\n', i); end
    fprintf(fid,'\\end{bmatrix}=10^{%d}\\begin{bmatrix}\n', pe);
    for i=1:6, fprintf(fid,'%+.4f \\\\\n', d(i)/10^pe); end
    fprintf(fid,'\\end{bmatrix}.\n\\]\n\n');

    % --- Vmat 表(共用)---
    fprintf(fid,'\\noindent\\textbf{Sensor voltages} $v_{jk}$~[V] (row $=$ sensor pole, column $=$ excited pole; diagonal $=$ self-actuation):\n\n');
    fprintf(fid,'\\begin{table}[htbp]\\centering\\small\n\\begin{tabular}{c rrrrrr}\n\\toprule\n');
    fprintf(fid,'sensor$\\backslash$excite & P1 & P2 & P3 & P4 & P5 & P6 \\\\\n\\midrule\n');
    for i=1:6
        fprintf(fid,'P%d', i);
        for j=1:6
            if i==j, fprintf(fid,' & \\cellcolor{yellow!20}$%+.3f$', Vp(i,j));
            else,    fprintf(fid,' & $%+.3f$', Vp(i,j)); end
        end
        fprintf(fid,' \\\\\n');
    end
    fprintf(fid,'\\bottomrule\n\\end{tabular}\n\\end{table}\n\n');

    fprintf(fid,'\\noindent The sensor-driven charge model (6 parameters $\\mathbf{d}$) reproduces the FEM field over $R\\le%d\\,\\mu$m with a relative RMSE of $%.2f\\%%$ (identical for both the gain and no-gain forms --- they fit the same field). It is coarser than the unconstrained $\\widehat{\\mathbf{K}}_I$ fit (36 DOF, $\\sim$1--3\\%%) because the per-simulation charges are tied to the sensor readings.\n\n', round(S.R_select*1e6), S.nrmse_sensor);
    fprintf(fid,'\\end{document}\n');
    fclose(fid);
end
