function write_KH_tex(tex_path, tag, src, dd, gF, KH, Ra, S)
% WRITE_KH_TEX  出 derivation.pdf 流程的 ĝ_F / K̂_H standalone LaTeX(tag='v2'/'final')。
%   (ported verbatim from gen_KH_latex.m local function)
    fid = fopen(tex_path,'w');
    fprintf(fid,'%% Auto-generated by sensor_d/main.m (write_KH_tex) -- derivation.pdf flow (g_F, K_H) from sensor d [%s]\n', tag);
    fprintf(fid,'\\documentclass[11pt,a4paper]{article}\n');
    fprintf(fid,'\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\usepackage{booktabs}\n\\usepackage{xcolor,colortbl}\n');
    fprintf(fid,'\\begin{document}\n\n');
    fprintf(fid,'\\section*{Sensor current-coupling: $\\widehat{g}_F$ and $\\widehat{\\mathbf{K}}_H$ (%s)}\n\n', tag);

    fprintf(fid,'\\noindent Flow (\\emph{derivation.pdf}): magnetic charge $\\widehat{\\mathbf{Q}}_j=\\tfrac{1}{\\mu_0}\\mathbf{D}\\mathbf{V}_j$ ($\\mathbf{D}=\\mathrm{diag}(\\mathbf{d})$). With $\\widehat{\\mathbf{Q}}=\\widehat{g}_F\\widehat{\\mathbf{K}}_H\\mathbf{F}$,\n');
    fprintf(fid,'\\[\\widehat{g}_F\\widehat{\\mathbf{K}}_H=\\tfrac{1}{\\mu_0}\\mathbf{D}\\mathbf{V}\\mathbf{F}^{\\top}(\\mathbf{F}\\mathbf{F}^{\\top})^{-1}=\\mathbf{H},\\quad (\\widehat{\\mathbf{K}}_H)_{11}=\\tfrac{5}{6}\\Rightarrow \\widehat{g}_F=\\tfrac{6}{5}h_{11},\\ \\widehat{\\mathbf{K}}_H=\\tfrac{5}{6h_{11}}\\mathbf{H}.\\]\n');
    fprintf(fid,'with $\\widehat{g}_F=N_c/(\\mu_0 R_a)$. Input $\\mathbf{d}$ from: %s; $\\widehat{\\ell}=%.3f$~mm.\n\n', src, S.ell_hat*1e3);

    % g_F and R_a
    fprintf(fid,'\\[\n\\widehat{g}_F = %.4e, \\qquad R_a = \\frac{N_c}{\\mu_0\\,\\widehat{g}_F} = %.4e~\\mathrm{A^{-1}}\\ (N_c=%d).\n\\]\n\n', gF, Ra, S.S_hall*0+70);

    % K_H matrix
    fprintf(fid,'\\[\n\\widehat{\\mathbf{K}}_H =\n\\begin{bmatrix}\n');
    for i=1:6
        fprintf(fid,'%+.4f',KH(i,1));
        for j=2:6, fprintf(fid,' & %+.4f',KH(i,j)); end
        if i<6, fprintf(fid,' \\\\\n'); else, fprintf(fid,'\n'); end
    end
    fprintf(fid,'\\end{bmatrix}\\quad(\\text{row}=\\text{charge pole},\\ \\text{col}=\\text{excited pole},\\ (\\widehat{\\mathbf{K}}_H)_{11}=\\tfrac{5}{6}).\n\\]\n\n');

    fprintf(fid,'\\noindent\\textbf{Note.} $\\widehat{\\mathbf{K}}_H$ is identical for both $d$ cases ($g_H$ cancels in $\\mathbf{H}/\\widehat{g}_F$); only $\\widehat{g}_F$ differs by $g_H$ ($\\widehat{g}_F^{\\,\\mathrm{v2}}=g_H\\,\\widehat{g}_F^{\\,\\mathrm{final}}$, $g_H=%.4e~\\mathrm{m^{-2}}$). The $b=g_H S V d$ (hw.pdf / final) pairing is the physical one --- its $R_a$ matches the page-1 charge-fit reluctance. Sensor model relative RMSE $=%.2f\\%%$.\n\n', S.gH, S.nrmse_sensor);
    fprintf(fid,'\\end{document}\n');
    fclose(fid);
end
