%% main_singlepole_bias.m -- single-pole (P1) WITH-bias point-charge fit {ell, e_y, e_z, ghat_I}
%  no_fix_l 的單極版：電荷離軸位移 pc_hat=[1, e_y, e_z]（軸向鎖 1 破 ell<->gI 簡併）。
%  模型：B(p) = ghat_I * I * (p/ell - pc_hat)/|p/ell - pc_hat|^3
%  3 形狀（filled / halfcut / tipcut）各 fit {ell, e_y, e_z, ghat_I}；取樣 R<=150µm 球（WP 為心）。
%  +x mesh：極軸=+x、WP 在原點，資料免 R_act 旋轉、免 z-shift（沿用 current_base 的 load_singlepole）。
%  ell 抓軸向（tipcut）、(e_y,e_z) 抓形狀橫向不對稱（halfcut z-cut -> e_z != 0）。
%  all-source：coil 電流在 mesh 已翻向 -> raw FEM 即 source（Bx@WP<0）-> SGN=+1。
%  對照無-bias（current_base/main_singlepole）：bias 讓 halfcut 誤差明顯下降。
%  輸出：data/singlepole_bias_fit.mat + results/singlepole_bias_fit.pdf（表：ell、e_y、e_z、ghat_I、cost J [mT^2]）。

clear; clc;

%% ---- config ----
SHAPES = {'filled','halfcut','tipcut'};
R_fit  = 150e-6;      % 取樣半徑 [m]（與無-bias 版一致）
I      = 1;           % drive current [A] = FEM 激發（fit-current-matches-sim）

%% ---- paths ----
TREE     = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\Calibration_using_FEM_modeling\current_base';
FIX_MFUN = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\Calibration_using_FEM_modeling\current_base\code\main_function';  % load_singlepole
addpath('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\backup\hexapole-long2016\analysis');   % mt_constants
addpath(FIX_MFUN);                                                                              % load_singlepole (reuse)
addpath(fullfile(TREE,'code','main_function'));                                                 % fit_singlepole_bias
DATA   = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\ANSYS_data\long2016_hexapole_halfcut\data\coil1\singlepole';
resdir = fullfile(TREE,'results','eighteen_param');   if ~exist(resdir,'dir'); mkdir(resdir); end

%% ---- constants + frame (+x mesh: pole axis = +x, WP at ORIGIN) ----
cnst = mt_constants();
cnst.SPH_OFST = 0;                                  % +x mesh: WP at ORIGIN (no z-shift)
SGN  = +1;                                          % FEM Bx@WP<0 = already source -> no flip
fprintf('single-pole BIAS fit (+x frame), SGN=%+d, R<=%dum\n', SGN, round(R_fit*1e6));

%% ---- fit each shape ----
ns = numel(SHAPES);
ell_um = zeros(1,ns); ey = zeros(1,ns); ez = zeros(1,ns); gI = zeros(1,ns);
Jcost  = zeros(1,ns); errpct = zeros(1,ns); Nnode = zeros(1,ns);
for s = 1:ns
    [Pw, BmT] = load_singlepole(fullfile(DATA, SHAPES{s}), cnst, 'tip');   % R<2mm ball @ WP
    Pa = Pw;  Ba = SGN * BmT;                        % +x/WP-origin frame, all-source
    in = vecnorm(Pa,2,2) <= R_fit;  Pa = Pa(in,:);  Ba = Ba(in,:);
    Nnode(s) = size(Pa,1);
    [ell, eyy, ezz, g, J, ~, Bmod] = fit_singlepole_bias(Pa, Ba, I);
    ell_um(s) = ell*1e6;  ey(s) = eyy;  ez(s) = ezz;  gI(s) = g;  Jcost(s) = J;
    errpct(s) = mean(vecnorm(Bmod-Ba,2,2) ./ vecnorm(Ba,2,2)) * 100;      % 逐點向量誤差 % 平均
    fprintf('%-8s | N=%5d | ell=%.2f um | e_y=%+.4f | e_z=%+.4f | ghat_I=%.4f mT/A | mean err=%.3f%% | J=%.4g\n', ...
            SHAPES{s}, Nnode(s), ell_um(s), ey(s), ez(s), gI(s), errpct(s), Jcost(s));
end

%% ---- 存 fit 結果 .mat（無因次 ey/ez 供 magerr + 側視圖重算 B_model）----
datadir = fullfile(TREE,'data');  if ~exist(datadir,'dir'); mkdir(datadir); end
save(fullfile(datadir,'singlepole_bias_fit.mat'), 'SHAPES','ell_um','ey','ez','gI', ...
     'Jcost','errpct','Nnode','R_fit','I');

%% ---- 輸出 PDF（純結果表；e_y,e_z 用 µm 物理偏移 = ℓ̂·e；.tex -> xelatex -> 只留 .pdf）----
emit_singlepole_bias_pdf(SHAPES, ell_um, ell_um.*ey, ell_um.*ez, gI, Jcost, Nnode, R_fit, I, resdir);

%% ================= local functions =================
function emit_singlepole_bias_pdf(shapes, ell_um, ey_um, ez_um, gI, Jcost, Nnode, R_fit, I, out_dir)
    base = 'singlepole_bias_fit';
    tex_path = fullfile(out_dir, [base '.tex']);
    pdf_path = fullfile(out_dir, [base '.pdf']);
    fid = fopen(tex_path, 'w');
    fprintf(fid, '%% Auto-generated by main_singlepole_bias.m\n');
    fprintf(fid, '\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\begin{document}\n');
    fprintf(fid, '\\begin{center}\\large\\textbf{Single-pole (P1) point-charge fit with transverse bias}\\end{center}\n');
    fprintf(fid, '\\[\n B(p) = \\hat{g}_I\\, I\\, \\dfrac{p/\\hat{\\ell} - \\hat{p}_c}{|p/\\hat{\\ell} - \\hat{p}_c|^{3}},\\quad p_c=(\\hat{\\ell},\\,e_y,\\,e_z),\\quad R\\le %d~\\mu\\mathrm{m},\\quad I=%g~\\mathrm{A}\n\\]\n', round(R_fit*1e6), I);
    fprintf(fid, '\\begin{center}\n\\begin{tabular}{lcccccc}\n\\hline\n');
    fprintf(fid, 'shape & $\\hat{\\ell}~[\\mu\\mathrm{m}]$ & $e_y~[\\mu\\mathrm{m}]$ & $e_z~[\\mu\\mathrm{m}]$ & ${}^{B}\\hat{g}_{I}~[\\mathrm{mT/A}]$ & cost $J~[\\mathrm{mT}^2]$ & $N$ \\\\\n\\hline\n');
    for s = 1:numel(shapes)
        fprintf(fid, '%s & %.2f & %+.2f & %+.2f & %.4f & %.4g & %d \\\\\n', ...
                shapes{s}, ell_um(s), ey_um(s), ez_um(s), gI(s), Jcost(s), Nnode(s));
    end
    fprintf(fid, '\\hline\n\\end{tabular}\n\\end{center}\n');
    fprintf(fid, '\\noindent\\small Fitted point-charge position $p_c=(\\hat{\\ell},e_y,e_z)$ in the +x single-pole frame (WP at origin, pole axis $+x$), all in $\\mu$m. $\\hat{\\ell}$ = axial depth ($x$); $(e_y,e_z)$ = transverse offset capturing tip-shape asymmetry (e.g.\\ halfcut $e_z<0$). A single monopole has only 3 position DOF, so no separate axial bias $e_x$ (degenerate with $\\hat{\\ell}$). cost $J=\\sum_i |B_{\\mathrm{mod}}(p_i)-B_{\\mathrm{FEM}}(p_i)|^2$ (the lsqnonlin objective) over real FEM nodes ($R\\le %d~\\mu$m).\n', round(R_fit*1e6));
    fprintf(fid, '\\end{document}\n');
    fclose(fid);
    xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
    [st, so] = system(sprintf('"%s" -interaction=nonstopmode -halt-on-error -output-directory="%s" "%s"', xelatex, out_dir, tex_path));
    if st~=0 || ~exist(pdf_path,'file'); fprintf('%s\n', so); error('xelatex 編譯失敗'); end
    for e = {'.tex','.aux','.log','.out'}
        f = fullfile(out_dir, [base e{1}]);  if exist(f,'file'); delete(f); end
    end
    fprintf('已存 %s\n', pdf_path);
end
