function sweep_singlepole_tipcut(x_list)
% SWEEP_SINGLEPOLE_TIPCUT  掃描 tipcut 切面 x（500..550µm）逐例做 +x 單極 monopole fit。
%   每例讀 data/coil1/singlepole/tipcut_sweep/tipcut_x<um>/{coord,bfield}_tip.dat，
%   R_fit=150µm 內 fit {ℓ̂, ᴮĝ_I}（沿用 load_singlepole + fit_singlepole；d̂=[1,0,0]、SGN=+1、I=1）。
%   → data/singlepole_tipcut_sweep.mat + figures/singlepole_tipcut_sweep_{ell,gI}.png
%     + results/singlepole_tipcut_sweep.pdf（純結果表）。
%   用法：sweep_singlepole_tipcut()          預設 500:10:550（6 例）
%         sweep_singlepole_tipcut([500 525 550])  指定
    if nargin < 1 || isempty(x_list), x_list = 500:10:550; end

    addpath('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\backup\hexapole-long2016\analysis');   % mt_constants
    TREE = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\Calibration_using_FEM_modeling\current_base';
    addpath(fullfile(TREE,'code','main_function'));     % load_singlepole + fit_singlepole
    DATA = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\ANSYS_data\long2016_hexapole_halfcut\data\coil1\singlepole\tipcut_sweep';
    figdir = fullfile(TREE,'figures','single_param');  if ~exist(figdir,'dir'); mkdir(figdir); end
    resdir = fullfile(TREE,'results','single_param');  if ~exist(resdir,'dir'); mkdir(resdir); end

    cnst = mt_constants();  cnst.SPH_OFST = 0;           % +x mesh: WP at ORIGIN
    R_fit = 150e-6;  I = 1;  d_act = [1;0;0];  SGN = +1;

    n = numel(x_list);
    x_um = x_list(:).';  ell_um = nan(1,n);  gI = nan(1,n);  cost = nan(1,n);  Npt = zeros(1,n);
    for i = 1:n
        d = fullfile(DATA, sprintf('tipcut_x%d', x_um(i)));
        if ~isfile(fullfile(d,'coord_tip.dat')) || ~isfile(fullfile(d,'bfield_tip.dat'))
            fprintf('x=%d : missing .dat, skip\n', x_um(i));  continue;
        end
        [Pw, BmT] = load_singlepole(d, cnst, 'tip');
        Pa = Pw;  Ba = SGN * BmT;                        % +x/WP 框、all-source（SGN=+1）
        in = vecnorm(Pa,2,2) <= R_fit;  Pa = Pa(in,:);  Ba = Ba(in,:);
        [ell, g, J] = fit_singlepole(Pa, Ba, d_act, I);
        ell_um(i) = ell*1e6;  gI(i) = g;  cost(i) = J;  Npt(i) = nnz(in);
        fprintf('x=%d | N=%d | ell=%.2f um | gI=%.4f mT/A | cost=%.4g\n', x_um(i), Npt(i), ell_um(i), gI(i), J);
    end

    save(fullfile(TREE,'data','singlepole_tipcut_sweep.mat'), 'x_um','ell_um','gI','cost','Npt','R_fit','I');
    plot_one(x_um, ell_um, '$\hat{\ell}\;(\mathrm{\mu m})$',        fullfile(figdir,'singlepole_tipcut_sweep_ell.png'));
    plot_one(x_um, gI,     '$^{B}\hat{g}_I\;(\mathrm{mT/A})$',      fullfile(figdir,'singlepole_tipcut_sweep_gI.png'));
    emit_sweep_pdf(x_um, ell_um, gI, cost, Npt, R_fit, I, resdir);   % 純結果表 -> results/singlepole_tipcut_sweep.pdf
end

function plot_one(x, y, ylab, out)
    ok = ~isnan(y);
    fig = figure('Color','w','Position',[100 100 820 600]);  ax = axes(fig);
    plot(ax, x(ok), y(ok), '-o', 'LineWidth',2.2, 'MarkerSize',6, ...
         'Color',[0.20 0.30 0.70], 'MarkerFaceColor',[0.20 0.30 0.70]);
    set(ax,'FontSize',16,'FontWeight','bold','LineWidth',2,'TickLength',[.018 .018]);
    box(ax,'on'); grid(ax,'off');
    xt = get(ax,'XTick'); set(ax,'XTick',xt(1:2:end));
    yt = get(ax,'YTick'); set(ax,'YTick',yt(1:2:end));
    xlabel(ax,'tip cut x (\mum)','FontWeight','bold');
    ylabel(ax, ylab, 'FontWeight','bold', 'Interpreter','latex');
    ax.Toolbar.Visible = 'off';
    exportgraphics(fig, out, 'Resolution', 200);
    fprintf('saved %s\n', out);
    close(fig);
end

function emit_sweep_pdf(x_um, ell_um, gI, cost, Npt, R_fit, I, out_dir)
% 純結果表 PDF（mirror main_singlepole.m 的 emit_singlepole_pdf；.tex -> xelatex -> 只留 .pdf）。
    tex_path = fullfile(out_dir, 'singlepole_tipcut_sweep.tex');
    pdf_path = fullfile(out_dir, 'singlepole_tipcut_sweep.pdf');
    fid = fopen(tex_path, 'w');
    fprintf(fid, '%% Auto-generated by sweep_singlepole_tipcut.m\n');
    fprintf(fid, '\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\begin{document}\n');
    fprintf(fid, '\\begin{center}\\large\\textbf{Single-pole tipcut sweep: monopole fit vs cut plane}\\end{center}\n');
    fprintf(fid, '\\[\n B(p) = \\hat{g}_I\\, I\\, \\dfrac{p/\\hat{\\ell} - \\hat{d}}{|p/\\hat{\\ell} - \\hat{d}|^{3}}, \\quad R\\le %d~\\mu\\mathrm{m}, \\quad I=%g~\\mathrm{A}\n\\]\n', round(R_fit*1e6), I);
    fprintf(fid, '\\begin{center}\n\\begin{tabular}{ccccc}\n\\hline\n');
    fprintf(fid, 'cut $x~[\\mu\\mathrm{m}]$ & $\\hat{\\ell}~[\\mu\\mathrm{m}]$ & ${}^{B}\\hat{g}_{I}~[\\mathrm{mT/A}]$ & $J~[\\mathrm{mT}^{2}]$ & $N$ \\\\\n\\hline\n');
    for i = 1:numel(x_um)
        fprintf(fid, '%d & %.2f & %.4f & %.4g & %d \\\\\n', x_um(i), ell_um(i), gI(i), cost(i), Npt(i));
    end
    fprintf(fid, '\\hline\n\\end{tabular}\n\\end{center}\n');
    fprintf(fid, '\\end{document}\n');
    fclose(fid);
    xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
    [st, so] = system(sprintf('"%s" -interaction=nonstopmode -halt-on-error -output-directory="%s" "%s"', xelatex, out_dir, tex_path));
    if st~=0 || ~exist(pdf_path,'file'); fprintf('%s\n', so); error('xelatex compile failed'); end
    for e = {'.tex','.aux','.log','.out'}
        f = fullfile(out_dir, ['singlepole_tipcut_sweep' e{1}]);  if exist(f,'file'); delete(f); end
    end
    fprintf('saved %s\n', pdf_path);
end
