%% gen_KI_alln_per_radius.m — per-radius LaTeX, UPDATED to the all-node deterministic fit.
%  Replaces the old bootstrap/trend source (cap-10000 sub-sample) with the
%  DETERMINISTIC ALL-IN-BALL-NODE fit produced yesterday (sweep_alln_vs_R.mat):
%  at each radius R every air node inside the R-ball is used, one unique lsqnonlin
%  fit -> {ell, gB, Khat}(R). Per-point error is recomputed over ALL in-ball nodes
%  (no sub-sampling). File names/format kept identical (fit_KI_R<Rum>.tex, R=40:10:500).
%  R=40 is not in the stored grid (50:5:500) -> refit on the fly (few nodes, fast).
%  SIGN: all-source (per .claude/rules/charge-model-source-convention.md): the stored
%  fit used a uniform -B negate, leaving upper poles P2/P4/P5 as sinks; flip those 3
%  COLUMNS for display so all diagonals are positive. Error uses the ORIGINAL Khat
%  (sign flip is a pure relabel, error unchanged).
clear; clc;
addpath('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\backup\hexapole-long2016\analysis');
results_root = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\ANSYS_data\long2016_hexapole_halfcut';
data_dir = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\fitting_trend';
texdir   = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\fitting_trend\scripts\per_radius';
if ~exist(texdir,'dir'); mkdir(texdir); end

cnst = mt_constants();
apdl_to_paper_idx = [1,3,6,5,2,4];
I = 1;                                   % each pole excited at 1 A (matches FEM excitation)
tip = [cnst.pole_tip_x; cnst.pole_tip_y; cnst.pole_tip_z_wp];
dhat = tip ./ vecnorm(tip);
coil_sign = [1 -1 1 -1 -1 1];            % all-source display flip over paper poles P1..P6

% stored deterministic sweep (R=50:5:500): ell_R, gB_R, Ksave
S = load(fullfile(data_dir,'sweep_alln_vs_R.mat'));
Rgrid = double(S.R_um(:));

% load 6 coils once (air, WP frame, source sign = negate)
fprintf('loading 6 coils ...\n');
C = struct('P',{},'Bn',{},'pj',{});
for k = 1:6
    cn = sprintf('coil%d',k);
    d = import_ansys_data(fullfile(results_root, cn, 'standard'),'wp',cn);
    air = filter_iron_nodes(d.x,d.y,d.z,cnst,struct('visualize',false));
    C(k).P  = [d.x(air), d.y(air), d.z(air)-cnst.SPH_OFST];
    C(k).Bn = -[d.bx(air), d.by(air), d.bz(air)];
    C(k).pj = apdl_to_paper_idx(k);
end

% lsqnonlin setup (only used for radii not in the stored grid, e.g. R=40)
freemask=true(6); freemask(1,1)=false;
opts=optimoptions('lsqnonlin','Display','off','MaxFunctionEvaluations',1e5, ...
    'MaxIterations',4e3,'FunctionTolerance',1e-20,'StepTolerance',1e-12);
Khat0 = eye(6)-ones(6)/6; ell0=0.5e-3; gB0=1;

R_out = 40:10:500;                        % keep the existing folder's radius set
for Rum = R_out
    R = Rum*1e-6;
    gi = find(Rgrid==Rum, 1);             % index into stored grid (empty if absent, e.g. R=40)
    if ~isempty(gi)                       % reuse stored deterministic fit
        ell = S.ell_R(gi); gB = S.gB_R(gi); Khat = S.Ksave(:,:,gi);
    else                                  % refit all-node at this radius (R=40)
        coil=struct('p',{},'bfem',{},'pj',{});
        for k=1:6
            ii=find(sum(C(k).P.^2,2)<R^2); Bn=C(k).Bn(ii,:);
            coil(k).p=C(k).P(ii,:); coil(k).bfem=[Bn(:,1);Bn(:,2);Bn(:,3)]; coil(k).pj=C(k).pj;
        end
        xf=lsqnonlin(@(x) resid_all(x,coil,dhat,I,freemask),[ell0*1e3;gB0;Khat0(freemask)],[],[],opts);
        [ell,gB,Khat]=unpack(xf,freemask);
    end

    % per-point relative error over ALL in-ball nodes (no sub-sampling)
    err=[]; npts=0;
    for k=1:6
        idx=find(sum(C(k).P.^2,2)<R^2);
        p=C(k).P(idx,:); Bfem=C(k).Bn(idx,:);
        pn=p/ell; w=gB*Khat(:,C(k).pj)*I; Bmod=zeros(size(p));
        for i=1:6, dd=pn-dhat(:,i).'; r3=vecnorm(dd,2,2).^3; Bmod=Bmod+w(i)*dd./r3; end
        err=[err; vecnorm(Bmod-Bfem,2,2)./vecnorm(Bfem,2,2)*100]; %#ok<AGROW>
        npts=npts+numel(idx);
    end
    mE=mean(err); medE=median(err); maxE=max(err);

    Kdisp = Khat .* coil_sign;            % all-source display
    dg = diag(Kdisp); noisy = (max(dg)>1.3)||(min(dg)<0.4);

    texfile = fullfile(texdir, sprintf('fit_KI_R%03d.tex', Rum));
    fid = fopen(texfile,'w');
    fprintf(fid,'%% Auto-generated by gen_KI_alln_per_radius.m -- DETERMINISTIC all-in-ball-node fit, ball R=%d um, all-source convention\n', Rum);
    fprintf(fid,'\\documentclass{article}\n\\usepackage{amsmath}\n\\begin{document}\n\n');
    fprintf(fid,'Fitting (sampling) region: ball $\\lVert\\mathbf{p}\\rVert \\le %d\\,\\mu\\mathrm{m}$ about the working point (WP); \\textbf{all %d in-ball air nodes} (every node, no sub-sampling) over the 6 coils.\n\n', Rum, npts);
    fprintf(fid,'Data: \\texttt{long2016\\_hexapole\\_halfcut} FEM, each pole excited at $%.1f\\,\\mathrm{A}$, $\\widehat{k}_{11}=5/6$ fixed. The fit is a single \\emph{deterministic} least-squares solve on all in-ball nodes (re-running gives identical numbers). Sign convention: \\emph{all-source} -- every excited pole emits ($\\mathbf{B}$ radiates out of its tip); upper-pole columns (P2,P4,P5) carry $\\mathrm{coil\\_sign}=-1$ so all diagonals are positive.\n\n', I);
    fprintf(fid,'\\[\n\\widehat{\\mathbf{K}}_I^{\\mathrm{FEM}} =\n\\begin{bmatrix}\n');
    for i = 1:6
        fprintf(fid,'%.4f',Kdisp(i,1)); for j = 2:6, fprintf(fid,' & %.4f',Kdisp(i,j)); end
        if i<6, fprintf(fid,' \\\\\n'); else, fprintf(fid,'\n'); end
    end
    fprintf(fid,'\\end{bmatrix}\n\\]\n\n');
    fprintf(fid,'\\[\n\\widehat{\\ell} = %.3f~\\mathrm{mm}, \\qquad \\widehat{g}_B = %s.\n\\]\n\n', ell*1e3, sci(gB));
    fprintf(fid,'Per-point fitting error over the region, $\\mathrm{Error}=\\dfrac{1}{N}\\sum_{i=1}^{N}\\dfrac{\\lvert\\mathbf{B}_{\\mathrm{model}}(\\mathbf{p}_i)-\\mathbf{B}_{\\mathrm{FEM}}(\\mathbf{p}_i)\\rvert}{\\lvert\\mathbf{B}_{\\mathrm{FEM}}(\\mathbf{p}_i)\\rvert}\\times100\\%%$ with $N=%d$ (all in-ball nodes):\n', npts);
    fprintf(fid,'\\[\n\\mathrm{Error} = %.2f\\%% \\quad(\\text{median } %.2f\\%%,\\ \\max %.2f\\%%).\n\\]\n\n', mE, medE, maxE);
    if noisy
        fprintf(fid,'\\emph{Note:} at this small radius the inverse problem is ill-conditioned, so the diagonal magnitudes are still noisy; the coupling matrix is best-determined for larger shells ($R\\gtrsim120\\,\\mu\\mathrm{m}$).\n\n');
    else
        fprintf(fid,'\\emph{Note:} all diagonal entries are positive (physical, emit) and off-diagonals negative with column sums $\\approx0$ (charge neutrality).\n\n');
    end
    fprintf(fid,'\\end{document}\n');
    fclose(fid);
    fprintf('wrote fit_KI_R%03d.tex  (ell=%.3f mm, gB=%.4e, Error=%.2f%%, diag=[%.2f %.2f %.2f %.2f %.2f %.2f])\n', Rum, ell*1e3, gB, mE, dg);
end
fprintf('\ndone: %d files in %s\n', numel(R_out), texdir);

%% local
function s = sci(x)
    if x==0, s='0'; return; end
    e = floor(log10(abs(x)));  s = sprintf('%.3f\\times10^{%d}', x/10^e, e);
end
function r = resid_all(x, coil, dhat, I, freemask)
    [ell, gB, Khat] = unpack(x, freemask); r=[];
    for k=1:numel(coil)
        pn=coil(k).p/ell; N=size(pn,1); B=zeros(3*N,1); w=gB*Khat(:,coil(k).pj)*I;
        for i=1:6
            dx=pn(:,1)-dhat(1,i); dy=pn(:,2)-dhat(2,i); dz=pn(:,3)-dhat(3,i);
            r3=(dx.^2+dy.^2+dz.^2).^1.5; B=B+w(i)*[dx./r3; dy./r3; dz./r3];
        end
        r=[r; B-coil(k).bfem]; %#ok<AGROW>
    end
end
function [ell, gB, Khat] = unpack(x, freemask)
    ell=x(1)*1e-3; gB=x(2); Khat=zeros(6); Khat(1,1)=5/6; Khat(freemask)=x(3:end);
end
