%% gen_KI_trend_per_radius.m — one LaTeX file per sampling radius for the trend sweep
%  Mirrors the style of charge_model_fitting/.../fit_KI_R###.tex, but for the FINE
%  cap-10000 trend (KI_trend_sweep.mat, R=40:10:500 um, 47 radii). For each radius it
%  emits fit_KI_R<Rum>.tex with the 6x6 Khat, ell, gB and the per-point fitting
%  error (mean/median/max), recomputed on the SAME sample the trend fit used
%  (per-coil cap 10000, rng(0)).
%  SIGN CONVENTION: "all-source" (per .claude/rules/charge-model-source-convention.md) --
%  every excited pole emits (B radiates OUT of its tip). The stored fit used a uniform
%  -B negate, which leaves upper poles (P2,P4,P5) as sinks (negative diagonal); we flip
%  those 3 COLUMNS for display so all diagonals are positive. coil_sign = [+1 -1 +1 -1 -1 +1]
%  over paper poles P1..P6 (lower P1/P3/P6 = +1, upper P2/P4/P5 = -1). This is a pure
%  per-pole sign relabel: the field-matching error is unchanged, so it is computed with
%  the ORIGINAL (unflipped) Khat and only the DISPLAYED matrix is sign-corrected.
%  Output: magnetic_sim/ANSYS/main/doc/fitting_trend/scripts/per_radius/fit_KI_R<Rum>.tex
clear; clc;
addpath('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\backup\hexapole-long2016\analysis');
results_root = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\ANSYS_data\long2016_hexapole_halfcut';
data_dir = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\fitting_trend';
texdir   = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\fitting_trend\scripts\per_radius';
if ~exist(texdir,'dir'); mkdir(texdir); end
S = load(fullfile(data_dir,'KI_trend_sweep.mat'));

cnst = mt_constants();
apdl_to_paper_idx = S.apdl_to_paper_idx;
I = S.I_actual;  Nmax = S.Nmax;
tip = [cnst.pole_tip_x; cnst.pole_tip_y; cnst.pole_tip_z_wp];
dhat = tip ./ vecnorm(tip);

% all-source sign convention: flip upper-pole columns P2,P4,P5 for display only
coil_sign = [1 -1 1 -1 -1 1];   % paper poles P1..P6 (lower +1, upper -1)

% load all 6 coils once (air-filtered, WP frame, source sign = negate)
fprintf('loading 6 coils ...\n');
C = struct('P',{},'Bn',{},'pj',{});
for k = 1:6
    cname = sprintf('coil%d',k);
    d = import_ansys_data(fullfile(results_root,cname),'wp',cname);
    air = filter_iron_nodes(d.x,d.y,d.z,cnst,struct('visualize',false));
    C(k).P  = [d.x(air), d.y(air), d.z(air)-cnst.SPH_OFST];
    C(k).Bn = -[d.bx(air), d.by(air), d.bz(air)];
    C(k).pj = apdl_to_paper_idx(k);
end

R_um = double(S.R_um(:)); nR = numel(R_um);
for ri = 1:nR
    Rum = R_um(ri);  R = Rum*1e-6;
    Khat = S.Khat_s(:,:,ri);  ell = S.ell_s(ri);  gB = S.gB_s(ri);

    % recompute per-point error on the same fit sample
    err = [];  npts = 0;
    for k = 1:6
        idx = find(sum(C(k).P.^2,2) < R^2);
        rng(0); if numel(idx) > Nmax, idx = idx(randperm(numel(idx),Nmax)); end
        p = C(k).P(idx,:);  Bfem = C(k).Bn(idx,:);
        pn = p/ell;  w = gB * Khat(:,C(k).pj) * I;  Bmod = zeros(size(p));
        for i = 1:6
            dd = pn - dhat(:,i).';  r3 = vecnorm(dd,2,2).^3;  Bmod = Bmod + w(i)*dd./r3;
        end
        err = [err; vecnorm(Bmod-Bfem,2,2)./vecnorm(Bfem,2,2)*100]; %#ok<AGROW>
        npts = npts + numel(idx);
    end
    mE = mean(err);  medE = median(err);  maxE = max(err);

    % apply all-source sign convention to the DISPLAYED matrix only (error already
    % computed with the original Khat; the per-pole flip leaves the error unchanged)
    Kdisp = Khat .* coil_sign;
    dg = diag(Kdisp);  noisy = (max(dg) > 1.3) || (min(dg) < 0.4);

    texfile = fullfile(texdir, sprintf('fit_KI_R%03d.tex', Rum));
    fid = fopen(texfile,'w');
    fprintf(fid,'%% Auto-generated by gen_KI_trend_per_radius.m -- trend sweep (cap 10000), ball R=%d um, all-source convention\n', Rum);
    fprintf(fid,'\\documentclass{article}\n\\usepackage{amsmath}\n\\begin{document}\n\n');
    fprintf(fid,'Fitting (sampling) region: ball $\\lVert\\mathbf{p}\\rVert \\le %d\\,\\mu\\mathrm{m}$ about the working point (WP); %d sample nodes (up to %d per coil $\\times$ 6 coils).\n\n', Rum, npts, Nmax);
    fprintf(fid,'Data: \\texttt{long2016\\_hexapole\\_halfcut} FEM, each pole excited at $%.1f\\,\\mathrm{A}$, $\\widehat{k}_{11}=5/6$ fixed, $\\widehat{g}_B^{(0)}=1$. Sign convention: \\emph{all-source} -- every excited pole emits ($\\mathbf{B}$ radiates out of its tip). The upper-pole columns (P2,P4,P5) carry $\\mathrm{coil\\_sign}=-1$ so all diagonal entries are positive (emission).\n\n', I);
    fprintf(fid,'\\[\n\\widehat{\\mathbf{K}}_I^{\\mathrm{FEM}} =\n\\begin{bmatrix}\n');
    for i = 1:6
        fprintf(fid,'%.4f',Kdisp(i,1)); for j = 2:6, fprintf(fid,' & %.4f',Kdisp(i,j)); end
        if i<6, fprintf(fid,' \\\\\n'); else, fprintf(fid,'\n'); end
    end
    fprintf(fid,'\\end{bmatrix}\n\\]\n\n');
    fprintf(fid,'\\[\n\\widehat{\\ell} = %.3f~\\mathrm{mm}, \\qquad \\widehat{g}_B = %s.\n\\]\n\n', ell*1e3, sci(gB));
    fprintf(fid,'Per-point fitting error over the region, $\\mathrm{Error}=\\dfrac{1}{N}\\sum_{i=1}^{N}\\dfrac{\\lvert\\mathbf{B}_{\\mathrm{model}}(\\mathbf{p}_i)-\\mathbf{B}_{\\mathrm{FEM}}(\\mathbf{p}_i)\\rvert}{\\lvert\\mathbf{B}_{\\mathrm{FEM}}(\\mathbf{p}_i)\\rvert}\\times100\\%%$ with $N=%d$ sample points:\n', npts);
    fprintf(fid,'\\[\n\\mathrm{Error} = %.2f\\%% \\quad(\\text{median } %.2f\\%%,\\ \\max %.2f\\%%).\n\\]\n\n', mE, medE, maxE);
    if noisy
        fprintf(fid,'\\emph{Note:} all diagonals positive (emit), but at this small radius the inverse problem is ill-conditioned, so the diagonal magnitudes are still noisy; the coupling matrix is best-determined for larger shells ($R\\gtrsim150\\,\\mu\\mathrm{m}$).\n\n');
    else
        fprintf(fid,'\\emph{Note:} all diagonal entries are positive (physical, emit) and off-diagonals negative with column sums $\\approx0$ (charge neutrality).\n\n');
    end
    fprintf(fid,'\\end{document}\n');
    fclose(fid);
    fprintf('wrote fit_KI_R%03d.tex  (ell=%.3f mm, gB=%.4e, Error=%.2f%%, diag=[%.2f %.2f %.2f %.2f %.2f %.2f])\n', Rum, ell*1e3, gB, mE, dg);
end
fprintf('\ndone: %d files in %s\n', nR, texdir);

function s = sci(x)
    if x==0, s='0'; return; end
    e = floor(log10(abs(x)));  s = sprintf('%.3f\\times10^{%d}', x/10^e, e);
end
