%% gen_nofixl_per_radius.m — per-radius LaTeX for the no_fix_l (18-param bias) sweep.
%  Reads sweep_nofixl_vs_R.mat (R=50:5:500, all in-ball nodes) and writes one
%  fit_KI_R<Rum>.tex per radius into per_radius/no_fix_l/. Each file lists the
%  6x6 K-bar_I, ell-hat, g_B-hat, and the bias e-hat (6x3, actuator frame).
%  NRMSE/Error is intentionally NOT reported (validation step, done separately).
%  SIGN: all-source (per .claude/rules/charge-model-source-convention.md): upper-pole
%  columns (P2/P4/P5) flipped for display so all K-bar_I diagonals are positive.
clear; clc;
addpath('G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\matlab\long2016_hexapole_halfcut\common');
model = 'long2016_hexapole_halfcut';

data_dir = matlab_path(model, 'charge_fit', 'fitting_trend');
texdir   = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\fitting_trend\scripts\per_radius\no_fix_l';
if ~exist(texdir,'dir'); mkdir(texdir); end

S  = load(fullfile(data_dir,'sweep_nofixl_vs_R.mat'));      % R_um, ell_R, gB_R, Ksave, Esave, npts, coil_sign, I_actual
cs = S.coil_sign;  I = S.I_actual;
R_out = double(S.R_um(:)).';                                % 50:5:500 (all stored radii)

for ii = 1:numel(R_out)
    Rum  = R_out(ii);
    ell  = S.ell_R(ii);  gB = S.gB_R(ii);  npts = S.npts(ii);
    Khat = S.Ksave(:,:,ii);
    Kdisp = Khat .* cs;                                     % all-source display (flip upper poles)
    E36 = reshape(S.Esave(:,ii), 3, 6);                    % 3x6: column k = e_k = [ekx;eky;ekz] (e1..e6), incl e6z
    dg  = diag(Kdisp);

    texfile = fullfile(texdir, sprintf('fit_KI_R%03d.tex', Rum));
    fid = fopen(texfile,'w');
    fprintf(fid,'%% Auto-generated by gen_nofixl_per_radius.m -- no_fix_l 18-param bias fit, ball R=%d um, all in-ball nodes, all-source convention\n', Rum);
    fprintf(fid,'\\documentclass{article}\n\\usepackage{amsmath}\n\\begin{document}\n\n');
    fprintf(fid,'Fitting (sampling) region: ball $\\lVert\\mathbf{p}\\rVert \\le %d\\,\\mu\\mathrm{m}$ about the working point (WP); \\textbf{all %d in-ball air nodes} (shared across the 6 coils, no sub-sampling) in the \\emph{actuator} frame.\n\n', Rum, npts);
    fprintf(fid,'Model: \\texttt{no\\_fix\\_l} 18-parameter (characteristic length $\\widehat{\\ell}$ + a $1\\times17$ bias $\\widehat{\\mathbf{e}}$, with $e_{6z}=e_{1x}-e_{2x}+e_{3y}-e_{4y}+e_{5z}$ constrained). Charges sit at $\\mathbf{p}_c = \\widehat{\\ell}\\,(\\mathbf{P}_c^{\\mathrm{base}}+\\mathbf{E}(\\widehat{\\mathbf{e}}))$ where $\\mathbf{P}_c^{\\mathrm{base}}=[+\\widehat{\\mathbf{u}}\\ -\\widehat{\\mathbf{u}}\\ +\\widehat{\\mathbf{v}}\\ -\\widehat{\\mathbf{v}}\\ +\\widehat{\\mathbf{w}}\\ -\\widehat{\\mathbf{w}}]$. Data: \\texttt{long2016\\_hexapole\\_halfcut} FEM, each pole excited at $%.1f\\,\\mathrm{A}$, $\\widehat{k}_{11}=5/6$ fixed. Sign convention: \\emph{all-source} -- every excited pole emits ($\\mathbf{B}$ radiates out of its tip); upper-pole columns (P2,P4,P5) carry $\\mathrm{coil\\_sign}=-1$ so all diagonals are positive.\n\n', I);
    % --- K-bar_I ---
    fprintf(fid,'\\[\n\\widehat{\\mathbf{K}}_I^{\\mathrm{FEM}} =\n\\begin{bmatrix}\n');
    for i = 1:6
        fprintf(fid,'%.4f',Kdisp(i,1)); for j = 2:6, fprintf(fid,' & %.4f',Kdisp(i,j)); end
        if i<6, fprintf(fid,' \\\\\n'); else, fprintf(fid,'\n'); end
    end
    fprintf(fid,'\\end{bmatrix}\n\\]\n\n');
    % --- ell, gB ---
    fprintf(fid,'\\[\n\\widehat{\\ell} = %.3f~\\mathrm{mm}, \\qquad \\widehat{g}_B = %s.\n\\]\n\n', ell*1e3, sci(gB));
    % --- bias e-hat (6x3, rows = P1..P6, cols = x,y,z in actuator frame; e6z is constrained) ---
    fprintf(fid,'Bias $\\widehat{\\mathbf{e}}=[\\,\\widehat{\\mathbf{e}}_1\\ \\widehat{\\mathbf{e}}_2\\ \\widehat{\\mathbf{e}}_3\\ \\widehat{\\mathbf{e}}_4\\ \\widehat{\\mathbf{e}}_5\\ \\widehat{\\mathbf{e}}_6\\,]$ (actuator frame, dimensionless; each column $\\widehat{\\mathbf{e}}_k=[e_{kx}\\ e_{ky}\\ e_{kz}]^{\\!\\top}$ is pole $P_k$''s offset 3-vector; $e_{6z}$ constrained):\n');
    fprintf(fid,'\\[\n\\widehat{\\mathbf{e}} =\n\\begin{bmatrix}\n');
    for r = 1:3
        fprintf(fid,'%+.4f',E36(r,1));
        for k = 2:6, fprintf(fid,' & %+.4f',E36(r,k)); end
        if r<3, fprintf(fid,' \\\\\n'); else, fprintf(fid,'\n'); end
    end
    fprintf(fid,'\\end{bmatrix}\n\\]\n\n');
    fprintf(fid,'\\emph{Note:} all diagonal entries are positive (physical, emit) and off-diagonals negative with column sums $\\approx0$ (charge neutrality).\n\n');
    fprintf(fid,'\\end{document}\n');
    fclose(fid);
    fprintf('wrote fit_KI_R%03d.tex  (ell=%.3f mm, gB=%.4e, diag=[%.2f %.2f %.2f %.2f %.2f %.2f])\n', Rum, ell*1e3, gB, dg);
end
fprintf('\ndone: %d files in %s\n', numel(R_out), texdir);

%% local
function s = sci(x)
    if x==0, s='0'; return; end
    e = floor(log10(abs(x)));  s = sprintf('%.3f\\times10^{%d}', x/10^e, e);
end
