%% gen_KI_trend_latex.m — emit the fitting-trend result LaTeX from KI_trend_sweep.mat
%  Reads the fine-radius sweep, computes the note.pdf Step-2 step-to-step errors,
%  and writes a self-contained KI_trend_results.tex (table + both figures + finding)
%  into magnetic_sim/ANSYS/main/doc/fitting_trend/.
clear; clc;
data_dir = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\fitting_trend';
out_tex  = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\fitting_trend\KI_trend_results.tex';
fig_dir  = 'G:/my_workspace/code/FEM_sim/magnetic_sim/ANSYS/main/figures/long2016_hexapole_halfcut';   % fwd slashes for LaTeX
S = load(fullfile(data_dir,'KI_trend_sweep.mat'));

R = double(S.R_um(:)); nR = numel(R);
% step-to-step errors (i = 2..nR); first row blank (no previous)
eK = nan(nR,1); egB = nan(nR,1); eL = nan(nR,1);
for i = 2:nR
    eK(i)  = norm(S.Khat_s(:,:,i)-S.Khat_s(:,:,i-1),'fro') / norm(S.Khat_s(:,:,i-1),'fro');
    egB(i) = (S.gB_s(i)  - S.gB_s(i-1))  / S.gB_s(i-1);
    eL(i)  = (S.ell_s(i) - S.ell_s(i-1)) / S.ell_s(i-1);
end

fid = fopen(out_tex,'w');
fprintf(fid,'%% Auto-generated by gen_KI_trend_latex.m -- charge-model fit vs sampling radius\n');
fprintf(fid,'\\documentclass[a4paper,11pt]{article}\n');
fprintf(fid,'\\usepackage{amsmath,amssymb,booktabs,graphicx,geometry,longtable}\n');
fprintf(fid,'\\geometry{margin=2.2cm}\n');
fprintf(fid,'\\graphicspath{{./}{%s/}}\n', fig_dir);   % current dir first (Overleaf), then local absolute
fprintf(fid,'\\begin{document}\n\n');
fprintf(fid,'\\section*{Charge-model fit stability vs.\\ sampling radius}\n');
fprintf(fid,'\\noindent Model: \\texttt{long2016\\_hexapole\\_halfcut}, 6 coils, $I=%.1f$\\,A. ', S.I_actual);
fprintf(fid,'Sampling region $=$ ball $\\lVert\\mathbf{p}\\rVert\\le R$ about the working point, ');
fprintf(fid,'$R = 40$--$500\\,\\mu$m in $10\\,\\mu$m steps (%d radii). At each $R$ the point-charge ', nR);
fprintf(fid,'model $\\mathbf{B}=\\hat g_B\\sum_i(\\sum_j\\hat k_{ij}I_j)\\,(\\mathbf{p}/\\hat\\ell-\\hat{\\mathbf d}_i)/\\lVert\\cdot\\rVert^3$ ');
fprintf(fid,'is fit for $\\{\\hat{\\mathbf K}_I^{\\mathrm{FEM}}\\,(\\hat k_{11}{=}5/6),\\ \\hat g_B,\\ \\hat\\ell\\}$ ');
fprintf(fid,'by \\texttt{lsqnonlin} over up to %d nodes/coil (source sign: FEM $\\mathbf B$ negated).\n\n', S.Nmax);

% --- Step 2 definitions ---
fprintf(fid,'\\paragraph{Step-to-step error (note Step 2).} Between consecutive radii ($i$ current, $j=i-1$):\n');
fprintf(fid,'\\[ \\varepsilon_{\\hat K}=\\frac{\\lVert\\hat{\\mathbf K}_I^{i}-\\hat{\\mathbf K}_I^{j}\\rVert_F}{\\lVert\\hat{\\mathbf K}_I^{j}\\rVert_F},\\qquad ');
fprintf(fid,'\\varepsilon_{\\hat g_B}=\\frac{\\hat g_B^{i}-\\hat g_B^{j}}{\\hat g_B^{j}},\\qquad ');
fprintf(fid,'\\varepsilon_{\\hat\\ell}=\\frac{\\hat\\ell^{i}-\\hat\\ell^{j}}{\\hat\\ell^{j}}. \\]\n\n');

% --- figures ---
fprintf(fid,'\\begin{figure}[h]\\centering\n');
fprintf(fid,'\\includegraphics[width=0.78\\linewidth]{KI_trend_convergence_logabs.png}\n');
fprintf(fid,'\\caption{Step-to-step change vs sampling radius (absolute value, log scale). ');
fprintf(fid,'$\\hat{\\mathbf K}_I$ drops from $\\sim76\\%%$ at $50\\,\\mu$m to $\\sim1\\%%$ by $\\sim150\\,\\mu$m and stays there.}\n');
fprintf(fid,'\\end{figure}\n\n');
fprintf(fid,'\\begin{figure}[h]\\centering\n');
fprintf(fid,'\\includegraphics[width=0.78\\linewidth]{KI_trend_convergence.png}\n');
fprintf(fid,'\\caption{Same data, signed relative change on a linear axis.}\n');
fprintf(fid,'\\end{figure}\n\n');

% --- finding ---
fprintf(fid,'\\paragraph{Finding.} The three fitted quantities are essentially converged ');
fprintf(fid,'(step change $<3\\%%$) for $R\\gtrsim150\\,\\mu$m; $\\hat\\ell$ then slowly drifts from ');
fprintf(fid,'$%.3f$ to $%.3f$\\,mm and the field RMS error grows from $%.1f\\%%$ to $%.1f\\%%$ as the ', ...
        S.ell_s(1)*1e3, S.ell_s(end)*1e3, S.err_s(1), S.err_s(end));
fprintf(fid,'ball reaches into the near field of the poles.\n\n');

% --- full table ---
fprintf(fid,'\\begin{longtable}{rrrrrrrr}\n\\caption{Per-radius fit and step-to-step errors.}\\\\\n\\toprule\n');
fprintf(fid,'$R$[$\\mu$m] & $N$ & $\\hat\\ell$[mm] & $\\hat g_B$ & err\\%% & $\\varepsilon_{\\hat K}$\\%% & $\\varepsilon_{\\hat g_B}$\\%% & $\\varepsilon_{\\hat\\ell}$\\%% \\\\\n\\midrule\n\\endhead\n');
for i = 1:nR
    if i==1
        fprintf(fid,'%d & %d & %.3f & %.4e & %.2f & -- & -- & -- \\\\\n', ...
            R(i), S.Ntot_s(i), S.ell_s(i)*1e3, S.gB_s(i), S.err_s(i));
    else
        fprintf(fid,'%d & %d & %.3f & %.4e & %.2f & %.2f & %+.2f & %+.2f \\\\\n', ...
            R(i), S.Ntot_s(i), S.ell_s(i)*1e3, S.gB_s(i), S.err_s(i), ...
            100*eK(i), 100*egB(i), 100*eL(i));
    end
end
fprintf(fid,'\\bottomrule\n\\end{longtable}\n\n');
fprintf(fid,'\\end{document}\n');
fclose(fid);
fprintf('wrote %s\n', out_tex);
