%% gen_KI_trend_N1000_latex.m — LaTeX for the FIXED-1000-node sweep (all 47 radii)
%  Same layout as gen_KI_trend_latex.m but reads KI_trend_sweep_N1000.mat (exactly
%  1000 nodes pooled over the 6 coils at every radius). Writes a self-contained
%  KI_trend_results_N1000.tex into magnetic_sim/ANSYS/main/doc/fitting_trend/.
clear; clc;
data_dir = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\fitting_trend';
out_tex  = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\fitting_trend\KI_trend_results_N1000.tex';
fig_dir  = 'G:/my_workspace/code/FEM_sim/magnetic_sim/ANSYS/main/figures/long2016_hexapole_halfcut';
S = load(fullfile(data_dir,'KI_trend_sweep_N1000.mat'));

R = double(S.R_um(:)); nR = numel(R);
eK = nan(nR,1); egB = nan(nR,1); eL = nan(nR,1);
for i = 2:nR
    eK(i)  = norm(S.Khat_s(:,:,i)-S.Khat_s(:,:,i-1),'fro') / norm(S.Khat_s(:,:,i-1),'fro');
    egB(i) = (S.gB_s(i)  - S.gB_s(i-1))  / S.gB_s(i-1);
    eL(i)  = (S.ell_s(i) - S.ell_s(i-1)) / S.ell_s(i-1);
end

fid = fopen(out_tex,'w');
fprintf(fid,'%% Auto-generated by gen_KI_trend_N1000_latex.m -- fixed-1000-node sweep\n');
fprintf(fid,'\\documentclass[a4paper,11pt]{article}\n');
fprintf(fid,'\\usepackage{amsmath,amssymb,booktabs,graphicx,geometry,longtable}\n');
fprintf(fid,'\\geometry{margin=2.2cm}\n');
fprintf(fid,'\\graphicspath{{./}{%s/}}\n', fig_dir);
fprintf(fid,'\\begin{document}\n\n');
fprintf(fid,'\\section*{Charge-model fit stability vs.\\ sampling radius (fixed 1000-node budget)}\n');
fprintf(fid,'\\noindent Model: \\texttt{long2016\\_hexapole\\_halfcut}, 6 coils, $I=%.1f$\\,A. ', S.I_actual);
fprintf(fid,'Sampling region $=$ ball $\\lVert\\mathbf{p}\\rVert\\le R$ about the working point, ');
fprintf(fid,'$R = 40$--$500\\,\\mu$m in $10\\,\\mu$m steps (%d radii). \\textbf{Unlike the capped sweep, ', nR);
fprintf(fid,'exactly $N=%d$ air nodes are drawn (pooled over the 6 coils) at every radius}, so the ', S.Nfix);
fprintf(fid,'node count is held constant (feasible because the smallest ball already has $>1000$ nodes). ');
fprintf(fid,'At each $R$ the point-charge model ');
fprintf(fid,'$\\mathbf{B}=\\hat g_B\\sum_i(\\sum_j\\hat k_{ij}I_j)\\,(\\mathbf{p}/\\hat\\ell-\\hat{\\mathbf d}_i)/\\lVert\\cdot\\rVert^3$ ');
fprintf(fid,'is fit for $\\{\\hat{\\mathbf K}_I^{\\mathrm{FEM}}\\,(\\hat k_{11}{=}5/6),\\ \\hat g_B,\\ \\hat\\ell\\}$ ');
fprintf(fid,'by \\texttt{lsqnonlin} (source sign: FEM $\\mathbf B$ negated).\n\n');

fprintf(fid,'\\paragraph{Step-to-step error.} Between consecutive radii ($i$ current, $j=i-1$):\n');
fprintf(fid,'\\[ \\varepsilon_{\\hat K}=\\frac{\\lVert\\hat{\\mathbf K}_I^{i}-\\hat{\\mathbf K}_I^{j}\\rVert_F}{\\lVert\\hat{\\mathbf K}_I^{j}\\rVert_F},\\qquad ');
fprintf(fid,'\\varepsilon_{\\hat g_B}=\\frac{\\hat g_B^{i}-\\hat g_B^{j}}{\\hat g_B^{j}},\\qquad ');
fprintf(fid,'\\varepsilon_{\\hat\\ell}=\\frac{\\hat\\ell^{i}-\\hat\\ell^{j}}{\\hat\\ell^{j}}. \\]\n\n');

fprintf(fid,'\\begin{figure}[h]\\centering\n');
fprintf(fid,'\\includegraphics[width=0.78\\linewidth]{KI_trend_convergence_N1000.png}\n');
fprintf(fid,'\\caption{Fixed 1000 nodes/radius: signed step-to-step relative change vs sampling radius.}\n');
fprintf(fid,'\\end{figure}\n\n');

fprintf(fid,'\\paragraph{Finding.} With a constant node budget the fitted values track the capped sweep ');
fprintf(fid,'closely ($\\hat\\ell$: $%.3f\\to%.3f$\\,mm; err: $%.1f\\to%.1f\\%%$ over $R=40\\to500\\,\\mu$m), ', ...
        S.ell_s(1)*1e3, S.ell_s(end)*1e3, S.err_s(1), S.err_s(end));
fprintf(fid,'confirming the convergence trend is physical and not an artifact of the growing sample size. ');
fprintf(fid,'The step-to-step metric is noisier (fewer points $\\Rightarrow$ larger estimator variance).\n\n');

fprintf(fid,'\\begin{longtable}{rrrrrrrr}\n\\caption{Per-radius fit and step-to-step errors (fixed 1000 nodes).}\\\\\n\\toprule\n');
fprintf(fid,'$R$[$\\mu$m] & $N$ & $\\hat\\ell$[mm] & $\\hat g_B$ & err\\%% & $\\varepsilon_{\\hat K}$\\%% & $\\varepsilon_{\\hat g_B}$\\%% & $\\varepsilon_{\\hat\\ell}$\\%% \\\\\n\\midrule\n\\endhead\n');
for i = 1:nR
    if i==1
        fprintf(fid,'%d & %d & %.3f & %.4e & %.2f & -- & -- & -- \\\\\n', ...
            R(i), S.Ntot_s(i), S.ell_s(i)*1e3, S.gB_s(i), S.err_s(i));
    else
        fprintf(fid,'%d & %d & %.3f & %.4e & %.2f & %.2f & %+.2f & %+.2f \\\\\n', ...
            R(i), S.Ntot_s(i), S.ell_s(i)*1e3, S.gB_s(i), S.err_s(i), ...
            100*eK(i), 100*egB(i), 100*eL(i));
    end
end
fprintf(fid,'\\bottomrule\n\\end{longtable}\n\n');
fprintf(fid,'\\end{document}\n');
fclose(fid);
fprintf('wrote %s\n', out_tex);
