function sp_emit(matfile)
%SP_EMIT  Single-pole calibration .mat -> LaTeX -> xelatex -> PDF (results/ keeps only the PDF).
%   sp_emit(matfile)
%   Output: results/<model>/<single|eighteen>/<base>_R<um>_<geom>.pdf
%   Contents (calibration-transfer-matrix-output.md, current base): g_I, l_hat, e_hat, RMS.
%   K_I_bar is 1 and H_I = g_I for a single excitation, so they are not printed.

    rec  = load(matfile);
    here = fileparts(mfilename('fullpath'));                  % .../function/single_pole
    CAL  = fileparts(fileparts(here));                        % .../Maxwell
    sub  = 'single'; if rec.USE_BIAS, sub = 'eighteen'; end
    out_dir = fullfile(CAL, 'results', rec.model, sub);
    if ~exist(out_dir, 'dir'), mkdir(out_dir); end
    stem     = sprintf('%s_R%d_%s', rec.base, round(rec.R_select*1e6), rec.GEOM);
    tex_path = fullfile(out_dir, [stem '.tex']);
    pdf_path = fullfile(out_dir, [stem '.pdf']);

    fid = fopen(tex_path, 'w');
    fprintf(fid, '%% Auto-generated by sp_emit.m\n');
    fprintf(fid, '\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\begin{document}\n');
    fprintf(fid, '\\[ {}^{B}\\hat{g}_{I} = %.4f~\\mathrm{mT/A} \\]\n', rec.gI_hat);
    fprintf(fid, '\\[ \\hat{\\ell} = %.1f~\\mu\\mathrm{m} \\]\n', rec.l_hat*1e6);
    if rec.USE_BIAS
        fprintf(fid, '\\[\n\\hat{e} = \\begin{bmatrix}\n%9.4f \\\\\n%9.4f \\\\\n%9.4f \\\\\n\\end{bmatrix}\n\\]\n', rec.e);
    end
    fprintf(fid, '\\[ \\mathrm{RMS} = \\sqrt{J/(3 \\cdot 1 \\cdot N)} = %.4g~\\mathrm{mT}, \\quad N = %d \\]\n', ...
            sqrt(rec.J / (3 * rec.npts)), rec.npts);
    fprintf(fid, '\\end{document}\n');
    fclose(fid);

    xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
    old = cd(out_dir);
    [st, so] = system(sprintf('"%s" -interaction=nonstopmode -halt-on-error "%s"', xelatex, tex_path));
    cd(old);
    if st ~= 0 || ~exist(pdf_path, 'file')
        disp(so); error('sp_emit: xelatex failed');
    end
    for ext = {'.tex','.aux','.log','.out'}
        f = fullfile(out_dir, [stem ext{1}]);
        if exist(f, 'file'), delete(f); end
    end
    fprintf('saved %s\n', pdf_path);
end
