function gen_B_matrix()
% GEN_B_MATRIX  依 doc/Solve_B_matrix/.../pdf/b_matrix.pdf 算 B matrix 並與參考矩陣比。
% -------------------------------------------------------------------------
% 放在本包（Hall_sensor_base_*）的 code/function/：自解 base（mfilename）→ 載本包
% data/calib_D_gap_200um.mat 的 Vmat_p → 出本包 results/B_matrix_result.pdf。
% 同一支同時在 fix / no_fix 兩包（各自解析各自 dir；Vmat_p 相同、輸出各自 results）。
%
% 公式（b_matrix.pdf）：
%   V_out = Sensitivity·B          （Sensitivity = 130 mV/mT；FEM 量到的 sensor 電壓）
%   I_in  = V_in·diag(K)  =>  V_in = I_in·diag(K)^{-1}
%   B_ij  = V_out,ij / V_in,ij       （**V_out、V_in 皆用 V**；無因次 V/V）
% 這裡：V_out = Vmat_p [mV]（gap_200um、basegap 網格對齊 CSV、10k 內插、all-source、S_hall=130）；
%   V_out[V]=Vmat_p/1000；V_in,j[V]=I_in/k_j；B_ij=(Vmat_p(i,j)/1000)·k_j/I_in。
% 另與使用者參考矩陣 B_ref 算 Frobenius 相對誤差 rel=‖B_fem−B_ref‖_F/‖B_ref‖_F。不產 csv。
% -------------------------------------------------------------------------

    %% ---- 參數 ----
    I_in   = 1;                                              % 激發電流 [A]
    S_hall = 130;                                            % 靈敏度 [mV/mT]（已含在 Vmat_p，僅註記）
    k = [0.3618, 0.3614, 0.3536, 0.3532, 0.3573, 0.3610];   % diag(K) [A/V]，欄 j = 激發 P1..P6（b_matrix.pdf）

    %% ---- 自解 base（本包 Hall_sensor_base_*）----
    here    = fileparts(mfilename('fullpath'));              % .../code/function
    base    = fileparts(fileparts(here));                   % .../Hall_sensor_base_*
    calib   = fullfile(base, 'data', 'calib_D_gap_200um.mat');
    out_dir = fullfile(base, 'results');
    if ~exist(out_dir,'dir'); mkdir(out_dir); end

    %% ---- V_out = 本包 Vmat_p ----
    S = load(calib, 'Vmat_p');                              % [mV]，列=sensor P1..P6、欄=激發 P1..P6
    Vout_mV = S.Vmat_p;

    %% ---- B_fem = V_out[V] / V_in[V]（欄 j 乘 k_j / I_in）----
    Vin_V = I_in ./ k;                                      % 1×6 [V]，V_in,j = I_in/k_j
    B_fem = (Vout_mV/1000) ./ Vin_V;                        % 廣播：每欄 j 除 V_in,j（= Vmat/1000·k_j/I_in）

    %% ---- 參考矩陣 B_ref（使用者提供影像；列/欄 = P1..P6）----
    %  ⚠ (3,3)=0.2795 依使用者影像；compute_vmatrix 內同位為 0.2995（差 0.02），以影像為準。
    B_ref = [ 0.2816 -0.0052 -0.0406 -0.0305 -0.0316 -0.0505;
             -0.0111  0.2659 -0.0423 -0.0666 -0.0756 -0.0346;
             -0.0470 -0.0332  0.2795 -0.0064 -0.0237 -0.0550;
             -0.0308 -0.0646 -0.0129  0.2348 -0.0833 -0.0193;
             -0.0411 -0.0661 -0.0217 -0.0760  0.2537 -0.0118;
             -0.0477 -0.0208 -0.0402 -0.0250 -0.0056  0.2302 ];

    %% ---- Frobenius 相對誤差 ----
    rel = norm(B_fem - B_ref, 'fro') / norm(B_ref, 'fro');

    %% ---- console ----
    pole = {'P1','P2','P3','P4','P5','P6'};
    fprintf('B_fem = V_out[V]/V_in[V]  (I_in=%g A, S_hall=%g mV/mT) | base=%s\n', I_in, S_hall, base);
    fprintf('V_in,j [V] = [%.4f %.4f %.4f %.4f %.4f %.4f]\n', Vin_V);
    fprintf('B_fem（列=sensor P1..P6，欄=激發 P1..P6）：\n');
    for i=1:6, fprintf('  % .4f % .4f % .4f % .4f % .4f % .4f\n', B_fem(i,:)); end
    fprintf('Frobenius 相對誤差 ‖B_fem−B_ref‖_F/‖B_ref‖_F = %.4f (%.2f%%)\n', rel, rel*100);

    %% ---- 輸出 PDF 到本包 results/ ----
    b = 'B_matrix_result';
    tex_path = fullfile(out_dir,[b '.tex']);
    pdf_path = fullfile(out_dir,[b '.pdf']);
    fid = fopen(tex_path,'w');
    fprintf(fid,'%% Auto-generated by gen_B_matrix.m\n');
    fprintf(fid,'\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\usepackage{amssymb}\n\\begin{document}\n');
    fprintf(fid,'\\begin{center}\\large\\textbf{B matrix (gap\\_200um) $B_{ij}=V_{out,ij}/V_{in,ij}$}\\end{center}\n');
    fprintf(fid,'\\[\n V_{out}=\\mathrm{Sensitivity}\\cdot B\\ (130~\\mathrm{mV/mT}),\\quad V_{in}=I_{in}\\,\\mathrm{diag}(K)^{-1},\\quad I_{in}=%g~\\mathrm{A}\n\\]\n', I_in);
    emit_labeled_matrix(fid, 'B_{\mathrm{fem}}', B_fem, pole, pole, 'auto', ...
        '$B_{\mathrm{fem}}$: FEM (gap\_200um, basegap mesh, 10k tet-interp, all-source). Row $i$ = sensor, column $j$ = excited pole; $V_{out}$, $V_{in}$ in V.');
    emit_labeled_matrix(fid, 'B_{\mathrm{ref}}', B_ref, pole, pole, 'auto', ...
        'Reference matrix (user-provided).');
    fprintf(fid,'\\[\n \\frac{\\lVert B_{\\mathrm{fem}}-B_{\\mathrm{ref}}\\rVert_F}{\\lVert B_{\\mathrm{ref}}\\rVert_F} = %.4f\\ (%.2f\\%%)\n\\]\n', rel, rel*100);
    fprintf(fid,'\\noindent\\small $k=\\mathrm{diag}(K)=[%.4f\\ %.4f\\ %.4f\\ %.4f\\ %.4f\\ %.4f]$ (P1--P6). $V_{in,j}=I_{in}/k_j$.\n', k);
    fprintf(fid,'\\end{document}\n');
    fclose(fid);

    xelatex = 'C:\Users\Kuo\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe';
    old = cd(out_dir);
    [st,so] = system(sprintf('"%s" -interaction=nonstopmode -halt-on-error "%s"', xelatex, tex_path));
    cd(old);
    if st~=0 || ~exist(pdf_path,'file'); fprintf('%s\n',so); error('xelatex 編譯失敗'); end
    for e = {'.tex','.aux','.log','.out'}, f = fullfile(out_dir,[b e{1}]); if exist(f,'file'); delete(f); end, end
    fprintf('已存 %s\n', pdf_path);
end

%% ---- local：渲染帶 P1..P6 表頭的 6×6 矩陣（含自動 10^n 因子）----
function emit_labeled_matrix(fid, name_tex, M, rowlab, collab, factor_mode, caption)
    if strcmp(factor_mode,'auto')
        mx = max(abs(M(:)));
        if mx > 0, e = floor(log10(mx)); else, e = 0; end
        if abs(e) >= 2, Ms = M / 10^e; fac = sprintf('10^{%d}\\,', e); else, Ms = M; fac = ''; end
    else
        Ms = M; fac = '';
    end
    fprintf(fid,'\\[\n%s = %s\\begin{array}{c|cccccc}\n', name_tex, fac);
    fprintf(fid,' ');
    for j = 1:6, fprintf(fid,'& %s ', collab{j}); end
    fprintf(fid,'\\\\\\hline\n');
    for i = 1:6
        fprintf(fid,'%s ', rowlab{i});
        for j = 1:6, fprintf(fid,'& %+9.4f ', Ms(i,j)); end
        fprintf(fid,'\\\\\n');
    end
    fprintf(fid,'\\end{array}\n\\]\n');
    fprintf(fid,'\\noindent\\small %s\n\n', caption);
end
