%% gen_d_latex.m
%  讀 calib_sensor_d.mat(calib_fem.m page-2 產出),出【兩份】standalone LaTeX:
%   (1) d_v2.tex    — Calibration using FEM modeling_V2.pdf(page 2,無增益):
%                     b_ij = S_i V_j d,   d = (Σ V S^T S V)^{-1}(Σ V S^T b)  → d~1e-3
%   (2) d_final.tex — hw.pdf(含增益 g_H):
%                     b_ij = g_H S_i V_j d, g_H = 1/(4πℓ̂²),
%                     d = 4πℓ̂²(Σ V S^T S V)^{-1}(Σ V S^T b)                  → d~1e-8
%  兩者同一個 fit,精確關係 d_v2 = d_final × g_H(由 mat 的 d=d_final、gH 還原)。
%  Output dir: magnetic_sim/ANSYS/main/doc/charge_model_fitting/long2016_hexapole_halfcut/scripts/
clear; clc;
mat_path = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\calib_sensor_d.mat';
tex_dir  = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\charge_model_fitting\long2016_hexapole_halfcut\scripts';
if ~exist(tex_dir,'dir'); mkdir(tex_dir); end

S = load(mat_path);                                  % d(=d_final), gH, Vmat, ell_hat, nrmse_sensor, S_hall, a2p, R_select
a2p = S.apdl_to_paper_idx;                           % coil j → paper pole
d_final = S.d;                                       % hw.pdf 版(含 g_H)
gH      = S.gH;                                       % 增益 g_H = 1/(4πℓ̂²)
d_v2    = d_final * gH;                               % Calibration_V2 版(無增益)= d_final × g_H(精確)

% 欄重排:Vmat 的「激發 coil」欄 → 「激發 paper pole P1..P6」欄
Vp = zeros(6,6);
for kc = 1:6, Vp(:, a2p(kc)) = S.Vmat(:, kc); end

% 刪除已過時的 d_sensor.tex(被 d_v2.tex 取代)
old = fullfile(tex_dir,'d_sensor.tex');
if exist(old,'file'), delete(old); end

% ---- (1) Calibration_V2 page-2(無增益)----
write_d_tex(fullfile(tex_dir,'d_v2.tex'), 'v2', d_v2, Vp, gH, S);
% ---- (2) hw.pdf / d_final(含增益)----
write_d_tex(fullfile(tex_dir,'d_final.tex'), 'final', d_final, Vp, gH, S);

fprintf('wrote d_v2.tex (no-gain, d~%.3e) and d_final.tex (gain, d~%.3e)\n', d_v2(1), d_final(1));
fprintf('check: d_v2 / d_final = %.4e  (should equal gH = %.4e)\n', d_v2(1)/d_final(1), gH);

%% ====================== 本地函式 ======================
function write_d_tex(tex_path, mode, d, Vp, gH, S)
% mode: 'v2'(無增益)或 'final'(含 g_H)
    fid = fopen(tex_path,'w');
    fprintf(fid,'%% Auto-generated by gen_d_latex.m -- Hall-sensor-based per-pole d (%s)\n', mode);
    fprintf(fid,'\\documentclass[11pt,a4paper]{article}\n');
    fprintf(fid,'\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\usepackage{booktabs}\n\\usepackage{xcolor,colortbl}\n');
    fprintf(fid,'\\begin{document}\n\n');
    fprintf(fid,'\\section*{Hall-sensor-based hexapole model --- per-pole calibration $\\mathbf{d}$}\n\n');

    % --- model 描述(兩版不同)---
    if strcmp(mode,'v2')
        fprintf(fid,'Model (\\emph{Calibration using FEM modeling\\_V2.pdf}, page 2 --- no explicit gain): $\\boldsymbol{\\varepsilon}_{ij}=\\mathbf{b}_{ij}-\\mathbf{S}_i\\mathbf{V}_j\\mathbf{d}$, i.e. $\\mathbf{b}_{ij}=\\sum_k d_k v_{jk}\\mathbf{s}_{ik}$. ');
        fprintf(fid,'Closed form $\\mathbf{d}=\\big(\\sum_{i,j}\\mathbf{V}_j\\mathbf{S}_i^{\\top}\\mathbf{S}_i\\mathbf{V}_j\\big)^{-1}\\big(\\sum_{i,j}\\mathbf{V}_j\\mathbf{S}_i^{\\top}\\mathbf{b}_{ij}\\big)$. The gain is absorbed into $\\mathbf{d}$; it relates to the gain version by $\\mathbf{d}=g_H\\,\\mathbf{d}_{\\mathrm{final}}$ with $g_H=%.4e~\\mathrm{m^{-2}}$.\n\n', gH);
    else
        fprintf(fid,'Model (\\emph{hw.pdf} --- explicit gain $g_H$): $\\boldsymbol{\\varepsilon}_{ij}=\\mathbf{b}_{ij}-g_H\\,\\mathbf{S}_i\\mathbf{V}_j\\mathbf{d}$, with $g_H=\\dfrac{k_m}{\\widehat{\\ell}^{2}\\mu_0}=\\dfrac{1}{4\\pi\\widehat{\\ell}^{2}}=%.4e~\\mathrm{m^{-2}}$ ', gH);
        fprintf(fid,'(from $\\widehat{\\mathbf{Q}}_j=\\widehat{\\boldsymbol{\\Phi}}_j/\\mu_0$, $\\mathbf{b}=\\tfrac{k_m}{\\widehat{\\ell}^2}\\mathbf{S}\\widehat{\\mathbf{Q}}$). ');
        fprintf(fid,'Closed form $\\mathbf{d}=\\dfrac{1}{g_H}\\big(\\sum_{i,j}\\mathbf{V}_j\\mathbf{S}_i^{\\top}\\mathbf{S}_i\\mathbf{V}_j\\big)^{-1}\\big(\\sum_{i,j}\\mathbf{V}_j\\mathbf{S}_i^{\\top}\\mathbf{b}_{ij}\\big)=4\\pi\\widehat{\\ell}^{2}\\big(\\cdots\\big)=\\mathbf{d}_{\\mathrm{V2}}/g_H$.\n\n');
    end

    % --- 設定 ---
    fprintf(fid,'\\noindent\\textbf{Settings.} $\\widehat{\\ell}=%.3f$~mm (from the $R\\le150\\,\\mu$m all-node fit), fit region $R\\le%d\\,\\mu$m, $S_{\\mathrm{hall}}=%g$~V/T, sensor at $4.572$~mm from apex $+\\,0.41$~mm off the surface. ', S.ell_hat*1e3, round(S.R_select*1e6), S.S_hall);
    fprintf(fid,'Sign convention: signed component $S_{\\mathrm{hall}}(\\mathbf{B}\\!\\cdot\\!\\mathbf{n}_+)$ along $\\mathbf{n}_+$ (outward from steel; lower $\\perp$ milled flat, upper $\\perp$ cone face), \\emph{all-source} (lower-pole excitations P1/P3/P6 sign-flipped, $\\equiv$ reversing those windings since $\\mathbf{B}$ is linear in current), so the diagonal (self-actuation) is positive.\n\n');

    % --- d 向量(動態共同指數)---
    pe = floor(log10(max(abs(d))));
    fprintf(fid,'\\[\n\\mathbf{d}=\\begin{bmatrix}\n');
    for i=1:6, fprintf(fid,'d_{\\mathrm{P%d}} \\\\\n', i); end
    fprintf(fid,'\\end{bmatrix}=10^{%d}\\begin{bmatrix}\n', pe);
    for i=1:6, fprintf(fid,'%+.4f \\\\\n', d(i)/10^pe); end
    fprintf(fid,'\\end{bmatrix}.\n\\]\n\n');

    % --- Vmat 表(共用)---
    fprintf(fid,'\\noindent\\textbf{Sensor voltages} $v_{jk}$~[V] (row $=$ sensor pole, column $=$ excited pole; diagonal $=$ self-actuation):\n\n');
    fprintf(fid,'\\begin{table}[htbp]\\centering\\small\n\\begin{tabular}{c rrrrrr}\n\\toprule\n');
    fprintf(fid,'sensor$\\backslash$excite & P1 & P2 & P3 & P4 & P5 & P6 \\\\\n\\midrule\n');
    for i=1:6
        fprintf(fid,'P%d', i);
        for j=1:6
            if i==j, fprintf(fid,' & \\cellcolor{yellow!20}$%+.3f$', Vp(i,j));
            else,    fprintf(fid,' & $%+.3f$', Vp(i,j)); end
        end
        fprintf(fid,' \\\\\n');
    end
    fprintf(fid,'\\bottomrule\n\\end{tabular}\n\\end{table}\n\n');

    fprintf(fid,'\\noindent The sensor-driven charge model (6 parameters $\\mathbf{d}$) reproduces the FEM field over $R\\le%d\\,\\mu$m with a relative RMSE of $%.2f\\%%$ (identical for both the gain and no-gain forms --- they fit the same field). It is coarser than the unconstrained $\\widehat{\\mathbf{K}}_I$ fit (36 DOF, $\\sim$1--3\\%%) because the per-simulation charges are tied to the sensor readings.\n\n', round(S.R_select*1e6), S.nrmse_sensor);
    fprintf(fid,'\\end{document}\n');
    fclose(fid);
end
