%% gen_KH_latex.m
%  依 derivation.pdf 流程,從 sensor 模型的 d 求 g_F 與 K_H,對【兩個 d case】各出一份 LaTeX。
%  流程(derivation.pdf):
%    磁荷 Q̂_j = (1/μ0) D V_j,  D=diag(d), V_j = sensor 電壓向量(第 j sim)
%    令 Q̂ = ĝ_F K̂_H F  ⇒  ĝ_F K̂_H = (1/μ0) D V F^T (F F^T)^{-1} = H
%    gauge (K̂_H)_11 = 5/6 ⇒ ĝ_F = (6/5) h11,  K̂_H = H/ĝ_F  (= 5/(6 h11) H)
%    其中 ĝ_F = N_c/(μ0 R_a) ⇒ R_a = N_c/(μ0 ĝ_F)
%  兩個 d:d_v2(Calibration_V2,無增益)與 d_final(hw.pdf,含 g_H);d_v2 = d_final × g_H。
%  ⇒ K̂_H 兩 case 相同(g_H 在 H/ĝ_F 抵消);ĝ_F 差一個 g_H(ĝ_F_v2 = g_H·ĝ_F_final)。
%  Output: magnetic_sim/ANSYS/main/doc/charge_model_fitting/long2016_hexapole_halfcut/scripts/KH_{v2,final}.tex
clear; clc;
addpath('G:\my_workspace\code\FEM_sim\magnetic_sim\hexapole-long2016\analysis');
mat_path = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\MATLAB_data\long2016_hexapole_halfcut\charge_fit\calib_sensor_d.mat';
tex_dir  = 'G:\my_workspace\code\FEM_sim\magnetic_sim\ANSYS\main\doc\charge_model_fitting\long2016_hexapole_halfcut\scripts';
if ~exist(tex_dir,'dir'); mkdir(tex_dir); end

cnst = mt_constants();
mu0 = cnst.mu_0; Nc = cnst.N_c;                       % μ0=4π e-7, N_c=70
S = load(mat_path);                                   % d(=d_final), gH, Vmat, ell_hat, apdl_to_paper_idx, nrmse_sensor
a2p = S.apdl_to_paper_idx;

d_final = S.d;  d_v2 = d_final * S.gH;                % 兩個 d
F = zeros(6,6); for j=1:6, F(a2p(j), j) = 1; end      % 電流矩陣(置換):第 j sim 激發 paper pole a2p(j)

cases = {'v2', d_v2, 'Calibration using FEM modeling\\_V2.pdf (no-gain $d$)'; ...
         'final', d_final, 'hw.pdf (gain $d$, $b=g_H S V d$)'};

for c = 1:2
    tag = cases{c,1};  dd = cases{c,2};  src = cases{c,3};
    G  = (1/mu0) * diag(dd) * S.Vmat;                 % 6x6 磁荷矩陣 Q̂(列=極 P1..P6,欄=sim/coil)
    H  = G * F.' / (F * F.');                          % H = Q̂ F^T (F F^T)^{-1}(欄重排成激發極 P1..P6)
    gF = (6/5) * H(1,1);                               % ĝ_F = (6/5) h11
    KH = H / gF;                                       % K̂_H = H/ĝ_F((1,1)=5/6)
    Ra = Nc / (mu0 * gF);                              % R_a = N_c/(μ0 ĝ_F)

    fprintf('[%s] ĝ_F = %.4e,  R_a = %.4e,  K̂_H(1,1) = %.4f\n', tag, gF, Ra, KH(1,1));
    write_KH_tex(fullfile(tex_dir, sprintf('KH_%s.tex',tag)), tag, src, dd, gF, KH, Ra, S);
end
fprintf('wrote KH_v2.tex + KH_final.tex\n');

%% ====================== 本地函式 ======================
function write_KH_tex(tex_path, tag, src, dd, gF, KH, Ra, S)
    fid = fopen(tex_path,'w');
    fprintf(fid,'%% Auto-generated by gen_KH_latex.m -- derivation.pdf flow (g_F, K_H) from sensor d [%s]\n', tag);
    fprintf(fid,'\\documentclass[11pt,a4paper]{article}\n');
    fprintf(fid,'\\usepackage[margin=1in]{geometry}\n\\usepackage{amsmath}\n\\usepackage{booktabs}\n\\usepackage{xcolor,colortbl}\n');
    fprintf(fid,'\\begin{document}\n\n');
    fprintf(fid,'\\section*{Sensor current-coupling: $\\widehat{g}_F$ and $\\widehat{\\mathbf{K}}_H$ (%s)}\n\n', tag);

    fprintf(fid,'\\noindent Flow (\\emph{derivation.pdf}): magnetic charge $\\widehat{\\mathbf{Q}}_j=\\tfrac{1}{\\mu_0}\\mathbf{D}\\mathbf{V}_j$ ($\\mathbf{D}=\\mathrm{diag}(\\mathbf{d})$). With $\\widehat{\\mathbf{Q}}=\\widehat{g}_F\\widehat{\\mathbf{K}}_H\\mathbf{F}$,\n');
    fprintf(fid,'\\[\\widehat{g}_F\\widehat{\\mathbf{K}}_H=\\tfrac{1}{\\mu_0}\\mathbf{D}\\mathbf{V}\\mathbf{F}^{\\top}(\\mathbf{F}\\mathbf{F}^{\\top})^{-1}=\\mathbf{H},\\quad (\\widehat{\\mathbf{K}}_H)_{11}=\\tfrac{5}{6}\\Rightarrow \\widehat{g}_F=\\tfrac{6}{5}h_{11},\\ \\widehat{\\mathbf{K}}_H=\\tfrac{5}{6h_{11}}\\mathbf{H}.\\]\n');
    fprintf(fid,'with $\\widehat{g}_F=N_c/(\\mu_0 R_a)$. Input $\\mathbf{d}$ from: %s; $\\widehat{\\ell}=%.3f$~mm.\n\n', src, S.ell_hat*1e3);

    % g_F and R_a
    fprintf(fid,'\\[\n\\widehat{g}_F = %.4e, \\qquad R_a = \\frac{N_c}{\\mu_0\\,\\widehat{g}_F} = %.4e~\\mathrm{A^{-1}}\\ (N_c=%d).\n\\]\n\n', gF, Ra, S.S_hall*0+70);

    % K_H matrix
    fprintf(fid,'\\[\n\\widehat{\\mathbf{K}}_H =\n\\begin{bmatrix}\n');
    for i=1:6
        fprintf(fid,'%+.4f',KH(i,1));
        for j=2:6, fprintf(fid,' & %+.4f',KH(i,j)); end
        if i<6, fprintf(fid,' \\\\\n'); else, fprintf(fid,'\n'); end
    end
    fprintf(fid,'\\end{bmatrix}\\quad(\\text{row}=\\text{charge pole},\\ \\text{col}=\\text{excited pole},\\ (\\widehat{\\mathbf{K}}_H)_{11}=\\tfrac{5}{6}).\n\\]\n\n');

    fprintf(fid,'\\noindent\\textbf{Note.} $\\widehat{\\mathbf{K}}_H$ is identical for both $d$ cases ($g_H$ cancels in $\\mathbf{H}/\\widehat{g}_F$); only $\\widehat{g}_F$ differs by $g_H$ ($\\widehat{g}_F^{\\,\\mathrm{v2}}=g_H\\,\\widehat{g}_F^{\\,\\mathrm{final}}$, $g_H=%.4e~\\mathrm{m^{-2}}$). The $b=g_H S V d$ (hw.pdf / final) pairing is the physical one --- its $R_a$ matches the page-1 charge-fit reluctance. Sensor model relative RMSE $=%.2f\\%%$.\n\n', S.gH, S.nrmse_sensor);
    fprintf(fid,'\\end{document}\n');
    fclose(fid);
end
